### PR TITLE
[Pytorch] Fix StringSupplier and TensorIdGetter returning pointers to local variables

### PR DESCRIPTION
**Pull request by HGuillemet**
JNI code of function pointers returning a String end with 
```c++
 return StringAdapter< char >(rptr, rsize, rowner);
```
Without this `@Cast`, the function returns a `std::basic_string<char>&` and the cast from `StringAdapter` returns a reference to a variable in the stack.
The `@Cast` makes the functions return a `char *` and the `StringAdapter` casting operator now allocates a new string in the heap.

Is there something more definitive to change in Generator about this ?

### CODE REVIEW

**Comment by HGuillemet** [comment]
Maybe we'd better take and return `BytePointer` instead of `String` for function pointers taking a returning a `std::string`.

**Comment by HGuillemet** [comment]
@saudet Any comment or could you merge ?

**Comment by saudet** [comment]
Looks OK I guess, but could you please fix these things in larger pull requests before merging them instead of doing a lot of mini pull requests like this?

**Comment by HGuillemet** [comment]
That's the inverse of what you prefer for javacpp repo.

Do you want me to append the commit of PR #1392 in this PR ?

**Comment by saudet** [comment]
No, I mean why did you not add that in pull #1360? If you just want to improve things further, yes, just start another mega pull request and modify everything you want in there, and I guess we won't merge it for a few months still before you stop "fixing" things? I mean, if you want to add new features and stuff, let's make multiple pull requests, if you just want to keep fixing things, fix them before merging the relevant pull request.

**Review by saudet — APPROVED** [review]

**Comment by HGuillemet** [comment]
Well, you did merge PR #1360. And the problems solved by this PR and PR 1360 were found afterward.
Shall I push more commits to the merged PR ?

**Comment by saudet** [comment]
No, I just mean try not to merge buggy code that you might want to fix later. If you don't mind that the code is buggy, I guess that's fine, but if you intend to fix it later, instead of opening many mini pull requests to fix everything later, try to not merge buggy code in the first place, that's all.

**Comment by HGuillemet** [comment]
Ok, but that were not the case. I didn't push a PR containing problems I was aware of and wanted to fix later. Did I ?

**Comment by saudet** [comment]
I'm not saying you're going it intentionally, I'm just saying you're creating a lot of unnecessary commits, so if you could stop doing that it would be nicer.

**Comment by mullerhai** [comment]
> Well, you did merge PR #1360. And the problems solved by this PR and PR 1392 were found afterward. Shall I push more commits to the merged PR ?

I want to know how to make pytorch -javacpp   train distribute  on one more machines，data parallel ？ and  openmpi  mpi  we need to bring to javacpp，thanks @HGuillemet  @saudet

**Pull request merged**
