### PR TITLE
add opencv build without openblas dependencies

### PR DESCRIPTION
**Pull request by n-kai-cj**
I'd like to add an option to build OpenCV without OpenBLAS dependencies.

- Add `exclude` argument to root `cppbuild.sh`
- Confirmed build success and run opencv without openblas.jar
  - build and run on windows-x86_64, windows-x86_64-gpu

build
`bash cppbuild.sh -platform windows-x86_64 -exclude openblas install opencv`
`mvn install -Djavacpp.platform=windows-x86_64 --projects opencv`

### CODE REVIEW

**Comment by saudet** [comment]
Please remove from the patch the files found under src/gen. They get regenerated anyway.

**Comment by n-kai-cj** [comment]
commit them.
BTW, how do I get this jar from https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/ or maven repository?
maybe I need to add something in `.appveyor.yml` and `.travis.yml`, but not sure how to add new argument `exclude`.

**Comment by saudet** [comment]
How about using an environment variable like HEADLESS so that we can run the build entering a single command like
`HEADLESS=1 mvn clean install`?

The builds are now done with GitHub Actions, so you can modify the files under `.github` to have the JAR files built from your fork deployed wherever you need them.

**Comment by saudet** [comment]
What about using `NOOPENBLAS` as environment variable to tweak the build? Does that sound good to you?

**Comment by n-kai-cj** [comment]
sorry for late.
Yes, that's better to me.

I was looking into the way to add something to `.github` files to make jar files. Ideally, I'd like to get the opencv jar without openblas by indicating like a `opencv_noopenblas-platforms` in pom.xml. But I'm not sure how to do that.

**Comment by saudet** [comment]
> I was looking into the way to add something to `.github` files to make jar files. Ideally, I'd like to get the opencv jar without openblas by indicating like a `opencv_noopenblas-platforms` in pom.xml. But I'm not sure how to do that.

The closest thing to that would be an "extension", such as the one defined in "platform/gpu/pom.xml", but this doesn't allow us to change the dependencies of the modules. There's just no way to do that with Maven... We could work around that by providing the "excludes" as part of the platform artifact in something like "platform/noopenblas/pom.xml" instead patching the main pom.xml file. I'm not sure that would work well, but if you would like to try it out, please do!

**Comment by n-kai-cj** [comment]
Yes, I've just noticed it seems not to be able to be achieved. If I succeed with your comments such as adding `exclude` and `platform/noopenblas/pom.xml`, we couldn't get opencv-gpu without openblas or we need more `platform/noopenblas/gpu/pom.xml`, right? I think it's not a good way.

Second ideal thing is to get each platforms of `opencv_noopenblas.jar` from https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/. Can we change the artifact jar file's name with command `mvn install` by editing pom.xml?

**Comment by saudet** [comment]
> Yes, I've just noticed it seems not to be able to be achieved. If I succeed with your comments such as adding `exclude` and `platform/noopenblas/pom.xml`, we couldn't get opencv-gpu without openblas or we need more `platform/noopenblas/gpu/pom.xml`, right? I think it's not a good way.

Right, it doubles the number of packages.

> Second ideal thing is to get each platforms of `opencv_noopenblas.jar` from https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/. Can we change the artifact jar file's name with command `mvn install` by editing pom.xml?

That's determined by the classifier name here:
https://github.com/bytedeco/javacpp-presets/blob/master/pom.xml#L348

**Comment by n-kai-cj** [comment]
Thank you! I'll try it later.

**Comment by saudet** [comment]
BTW, why do you need a version of OpenCV without OpenBLAS? Are you experiencing any issues with OpenBLAS?

**Comment by n-kai-cj** [comment]
No, I don't have particular reason. I just want to reduce the artifact size.

**Comment by saudet** [comment]
That will only reduce the overall size by 1/3rd. To reduce more, you'll need to disable other modules from OpenCV anyway...

**Comment by n-kai-cj** [comment]
Since openblas of master branch is upgraded, I have to change patch file.
I think it'll be unclear commit if I commit all changes from current master branch, so send another PR https://github.com/bytedeco/javacpp-presets/pull/987

Can I close this PR?

**Comment by saudet** [comment]
We can rebase the branch in those cases, no need to open a new PR, but
since you've already opened one, we can close this one, yes.

**Pull request closed without merging**
