### PR TITLE
Correct generation of Vec4iVector

### PR DESCRIPTION
**Pull request by jpsacha**
Fix for #717

### CODE REVIEW

**Comment by saudet** [comment]
Actually, I don't think we need it there at all because it's already here: https://github.com/bytedeco/javacpp-presets/blob/master/opencv/src/main/java/org/bytedeco/opencv/presets/opencv_core.java#L360
Can you check that?

**Comment by jpsacha** [comment]
`HoughLinesP` is declared with `Vec4iVector`, see:
https://github.com/bytedeco/javacpp-presets/blob/c0ccd115c19bac69b78cf298a87f67fe1caba80e/opencv/src/main/java/org/bytedeco/opencv/presets/opencv_imgproc.java#L69

The line you pointed declares `Scalar4i`
https://github.com/bytedeco/javacpp-presets/blob/31ab1070fcc9ae1590344d70eacb6731349c7585/opencv/src/main/java/org/bytedeco/opencv/presets/opencv_core.java#L360
It does not resolve issue with `Vec4iVector`/`HoughLinesP`

May be `Vec4iVector` should be deleted and `HoughLinesP` declared with `Scalar4i`?

**Comment by saudet** [comment]
Yes, but it should still work. Did you try to build it that way?

**Comment by jpsacha** [comment]
I do not rebuild it. I am using released versions.

**Comment by saudet** [comment]
Fixed in commit https://github.com/bytedeco/javacpp-presets/commit/03bc1166462eaafdba694853cb15398bfa0038ea, thanks for reporting!

**Pull request closed without merging**
