### PR TITLE
Update Maven Version For Triton Server README

### PR DESCRIPTION
**Pull request by dyastremsky**
The old version is no longer available, so this ticket updates the Maven version in the README.

### CODE REVIEW

**Comment by saudet** [comment]
Thanks! Let's use the archive instead to avoid this happening again:
https://archive.apache.org/dist/maven/maven-3/
/cc @jackyh

**Comment by dyastremsky** [comment]
My pleasure. Makes sense! I switched to the archive link (3.8.4) and tested that it's working

**Comment by saudet** [comment]
It looks like a new version of Triton has also just been released (21.12-py3), let's update that as well?
https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tritonserver

**Comment by dyastremsky** [comment]
Good eye. Done!

**Pull request merged**
