### PR TITLE
Add X265 multilib support for osx and linux-x86*

### PR DESCRIPTION
**Pull request by renderdude**
X265 supports API selectable internal compression depths of 8,10, or 12 bits. This commit enables building of multilib support for X265 on osx and linux-x86* and enables this feature in ffmpeg.

### CODE REVIEW

**Comment by saudet** [comment]
Thanks for the contribution! But it doesn't build:
```
ERROR: libx265 not found
```
The `$INSTALL_PATH` needs to be used to have make install them in the right place. BTW, instead of using a patch to modify `multilib.sh`, we could directly launch these multiple builds from `cppbuild.sh`. That would make it easier to test and fix.

**Comment by renderdude** [comment]
Which platform failed?

**Comment by saudet** [comment]
Linux, Fedora 27, but you'll see it on Travis CI with CentOS 6.

**Comment by saudet** [comment]
See here: https://travis-ci.org/bytedeco/javacpp-presets/jobs/436238096
That's failing because it doesn't find `cmake` though, we need to call `cmake3` on CentOS.

**Comment by renderdude** [comment]
I’m in the process of rewriting the code to inline it in cppbuild.sh and use INSTALL_PATH and $CMAKE. Should have a new pull request later today.

**Comment by saudet** [comment]
We can skip things like AVX for 32-bit builds. Those binaries are not used for performance anyway.

**Comment by renderdude** [comment]
So the last patch fixed the compile, but now it's erroring in deploy (XCode). As it doesn't appear to be related to this patch, I assume I can ignore.

**Comment by saudet** [comment]
Yes, it's looking good, thanks! I'd like to do the same with other platforms before merging this though. If you could give it a try, that'd be great.

**Comment by saudet** [comment]
Looking good! Builds are passing on Windows. Thanks!

**Comment by saudet** [comment]
This is pretty much it: https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments#android-arm-and-x86

It doesn't work? What message do you get with your crash?

**Comment by renderdude** [comment]
It gets to OpenSSL (I think, we really need a print statement indicating each step of the build), and dies with this:

SIXTY_FOUR_BIT_LONG mode
RC4 uses unsigned char

Configured for android64.
clang70clang70: error: unknown argument: '-mandroid'
: error: unknown argument: '-mandroid'
clang70: warning: -z text: 'linker' input unused [-Wunused-command-line-argument]

**Comment by renderdude** [comment]
It gets to OpenSSL (I think, we really need a print statement indicating each step of the build), and dies with this:

SIXTY_FOUR_BIT_LONG mode
RC4 uses unsigned char

Configured for android64.
clang70clang70: error: unknown argument: '-mandroid'
: error: unknown argument: '-mandroid'
clang70: warning: -z text: 'linker' input unused [-Wunused-command-line-argument]

**Comment by saudet** [comment]
Ah, you're trying to build with Clang, that won't work, keep using GCC.

You mean like echo statements in the script? We can add those sure, or just
enabling echo of the commands would be easier I think.

**Comment by renderdude** [comment]
The issue is that I’m using the cppbuild straight out of the box. So where it’s picking up clang I don’t know. My guess is that it’s an install issue. I’m using r18

Rather than echoing commands, I would have it output something like:

-------------------
Building zlib
-------------------

… compile output …

-------------------
Building Lame
-------------------

… compile output

At least that way it’s easier to detect which package failed, rather than hunting through the compile output looking for an include or install directory.

**Comment by renderdude** [comment]
The issue is that I’m using the cppbuild straight out of the box. So where it’s picking up clang I don’t know. My guess is that it’s an install issue. I’m using r18.

Rather than echoing commands, I would have it output something like:

-------------------
Building zlib
-------------------

… compile output …

-------------------
Building Lame
-------------------

… compile output

At least that way it’s easier to detect which package failed, rather than hunting through the compile output looking for an include or install directory.

**Comment by saudet** [comment]
r18 doesn't have GCC anymore, use r15c as per these instructions:
https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments#android-arm-and-x86

**Comment by saudet** [comment]
Everything should work pretty much as is with r15c, for now. We'll need to do something about Clang eventually when other projects like FFmpeg and TensorFlow start supporting it, but it's not really the case for now, unfortunately.

**Comment by saudet** [comment]
We can echo commands here and there too that's fine :+1: Thanks

**Comment by renderdude** [comment]
All of the android versions have been committed.

Mark

**Pull request merged**
