### PR TITLE
add ffmpeg-flv-support-hevc-opus.patch

### PR DESCRIPTION
**Pull request by nanguantong**

### CODE REVIEW

**Comment by saudet** [comment]
Please apply the patch in cppbuild.sh

**Comment by nanguantong** [comment]
> Please apply the patch in cppbuild.sh

Done.

**Comment by nanguantong** [comment]
Hi, @saudet , when can the release(or snapshot) version be generated?

**Comment by saudet** [comment]
Now that this is merged, the snapshots should appear as the builds finish: http://bytedeco.org/builds/

**Comment by nanguantong** [comment]
@saudet 
Could not find ffmpeg-5.1.1-1.5.8-SNAPSHOT-android-arm.jar (org.bytedeco:ffmpeg:5.1.1-1.5.8-SNAPSHOT:20220914.111940-49).
Searched in the following locations:
    https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/ffmpeg/5.1.1-1.5.8-SNAPSHOT/ffmpeg-5.1.1-1.5.8-20220914.111940-49-android-arm.jar

**Pull request merged**
