### PR TITLE
Enable Zimg for FFmpeg

### PR DESCRIPTION
**Pull request by callisto-jovy**
This should close [https://github.com/bytedeco/javacv/issues/1389](url) and allow for tonemapping with FFmpeg.

### CODE REVIEW

**Comment by callisto-jovy** [comment]
As the non-x86_64 builds are failing with the same error message, they must be missing a certain flag. Do you have an idea on what that could be? @saudet

**Comment by saudet** [comment]
> 2023-10-21T11:03:27.4134446Z require_pkg_config libzimg zimg >= 2.7.0 zimg.h zimg_get_api_version
> 2023-10-21T11:03:27.4134763Z check_pkg_config libzimg zimg >= 2.7.0 zimg.h zimg_get_api_version
> 2023-10-21T11:03:27.4135071Z test_pkg_config libzimg zimg >= 2.7.0 zimg.h zimg_get_api_version
> 2023-10-21T11:03:27.4135335Z false --exists --print-errors zimg >= 2.7.0
> 2023-10-21T11:03:27.4135609Z ERROR: zimg >= 2.7.0 not found using pkg-config

pkg-config doesn't work for cross compilation

**Comment by b005t3r** [comment]
I see that @callisto-jovy nearly figured it out, but I can't see from your comments what was the issue with the change they made.

**Comment by saudet** [comment]
We can't use pkg-config, unless you figure out a way to make it work well for cross compilation, Android, Windows, etc. It's usually easier to patch FFmpeg's configure to prevent it from using pkg-config

**Comment by saudet** [comment]
Superseded by pull #1481

**Pull request closed without merging**
