### PR TITLE
Added LLVM for Windows x86 and x86_64

### PR DESCRIPTION
**Pull request by Wolftein**
#305

### CODE REVIEW

**Comment by saudet** [comment]
Thanks for the contribution! Unfortunately, I wasn't able to get it to build following the instructions here:
https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments#windows-x86-and-x86_64

First, I get an error when decompressing the archives:
```
tar: cfe-4.0.0.src/test/Driver/Inputs/basic_cross_linux_tree/usr/x86_64-unknown-linux-gnu/bin/ld: Cannot create symlink to ‘ld.gold’: No such file or directory
tar: cfe-4.0.0.src/test/Driver/Inputs/basic_cross_linux_tree/usr/i386-unknown-linux-gnu/bin/ld: Cannot create symlink to ‘ld.gold’: No such file or directory
```

Ignoring that, I get a lot of errors from CMake about missing files... Would you have any additional instructions to get this working?

**Comment by Wolftein** [comment]
It looks like msys2 doesn't support creating symlink from a package file, can't find a solution to this, but a workaround would be copying all files from the windows LLVM folder or providing LLVM already compiled.

**Comment by saudet** [comment]
Actually, MSYS2 and Windows 10 do support symbolic links. We have to uncomment `MSYS=winsymlinks:nativestrict` from `mingw64.ini`, and run it as "Administrator". Is this what you did? Or how did you get it to build?

**Comment by Wolftein** [comment]
Already did that and still i'm unable to retrieve a symbolic link from a package file (Maybe is related to this?
 https://github.com/Alexpux/MSYS2-packages/issues/140).

I copied the include and lib folder (built in windows with the same command) into the llvm folder and then running maven.

**Comment by saudet** [comment]
So, let's forget about MSYS2. How did you build it if not by running
cppbuild.sh in MSYS2?

**Comment by Wolftein** [comment]
I removed the download, unpacking line from cppbuild.sh and copied everything from my llvm's windows folder. Then run cppbuild and maven.

**Comment by saudet** [comment]
And where do these files in your llvm folder come from? Did you extract the archive with something else like 7-Zip?

**Comment by Wolftein** [comment]
Yes, i extract them using 7-Zip

**Comment by saudet** [comment]
Ah, I see. MSYS2 also comes with a version of 7-Zip. I wonder if that one also works for extracting that archive from the command line, from inside the script...

**Comment by Wolftein** [comment]
What about instead of download llvm source code and compile it, provide the .lib files and then run javacpp? llvm takes 30+ minutes to compile (if using all cores) otherwise it takes more than 1hs.

**Comment by saudet** [comment]
Sure, where can we get the precompiled DLL?

**Comment by Wolftein** [comment]
I have both x86 and x86_64 llvm.lib precompiled, i could upload them to github and replace the script or i could send them to you, so you can upload them on your own repository

**Comment by saudet** [comment]
Are you planning on building and maintaining all future versions of LLVM this way?

If not, let's make a script to build those!

**Comment by saudet** [comment]
Marking as duplicate of #530

**Pull request closed without merging**
