### PR TITLE
use antrun maven plugin to run cppbuild scripts within the maven build

### PR DESCRIPTION
**Pull request by jjYBdx4IL**

### CODE REVIEW

**Comment by saudet** [comment]
Looks good, thanks! But the maven-antrun-plugin screws up the output of the script. exec-maven-plugin doesn't appear to have that problem, so could we use that instead? 

And we need to pass on the user-specified `javacpp.platform` property to the `-platform` option of the script. And I'll merge that in! thanks :)

**Comment by jjYBdx4IL** [comment]
yeah that's better

**Comment by saudet** [comment]
Looks good! So, could you squash this into one commit so it will merge cleanly?

BTW, the environment variables set aren't used for anything yet, so we could remove them, but if you'd like to keep them, let's make the names consistent. Something like the following maybe?
```xml
            <PROJECT_VERSION>${project.version}</PROJECT_VERSION>
            <PROJECT_BASEDIR>${project.basedir}</PROJECT_BASEDIR>
```
Thanks!

**Comment by jjYBdx4IL** [comment]
done

**Comment by saudet** [comment]
Thanks!

**Pull request merged**
