### PR TITLE
Correct linking of FlyCapture2 on Windows to work with v.2.12.3.2

### PR DESCRIPTION
**Pull request by jpsacha**

### CODE REVIEW

**Comment by saudet** [comment]
Thanks! Could you also update the archives for CI?

**Comment by jpsacha** [comment]
@saudet I do not have all those binary setups to pull binaries, especially x86 linux and arm.

@vb216 Do you have binaries for FlyCapture_2.12.3.2 for all those systems.

**Comment by vb216** [comment]
I don't have them.. went to their download website https://www.ptgrey.com/support/downloads and picked a camera at random, I can only see 2.13.3.31 downloads now, even trying a few different cameras. So looks like they've released a newer version in the meantime, and I can't see any historical downloads section

**Comment by saudet** [comment]
@vb216 Ok that's fine, let's go with 2.13 and @jpsacha will update this PR for that version. :)

**Comment by jpsacha** [comment]
@saudet I updated for latest released version 2.13. @vb216 please add the CI test binaries.

**Comment by vb216** [comment]
Was planning on adding a function into the ci script for it to unpack the unmodified SDKs.. not sure best way to get that into this pull request? Open to suggestions.. only can come up with average solutions so far. Meantime will get the code working

**Comment by saudet** [comment]
You should be able to push to his fork...? If not, @jpsacha could you give
him permission, if that's ok?

**Comment by vb216** [comment]
So I tested over here, https://travis-ci.org/vb216/javacpp-presets/builds/468367814, and it built OK, I've then just pushed that set of changes to the install-travis.sh.. looks like they're picked up on this pull request but some merge conflict - I think thats just an older flycap source file though? 
Should be easier in future now, the logic is added in to unpack any unmodified SDK file and put the files in required place to build.

**Comment by saudet** [comment]
Nope, the build is failing on Windows:
```
[ERROR] Failed to execute goal org.bytedeco:javacpp:1.4.4-SNAPSHOT:build (javacpp.parser) on project flycapture: Failed to execute JavaCPP Builder: Could not parse "FlyCapture2VideoDefs.h": File does not exist -> [Help 1]
```
https://ci.appveyor.com/project/Bytedeco/javacpp-presets/builds/21138224/job/gthj2pqu11j9957q

We'll need to fix this before we can merge.

**Pull request merged**
