### PR TITLE
Build MXNet under windows 

### PR DESCRIPTION
**Pull request by Neiko2002**
Several fixes for the new javacpp-preset version 1.2.5. Many of them have been discussed here:
https://github.com/bytedeco/javacpp-presets/issues/298

Additionally there is Windows support for MXNet.

### CODE REVIEW

**Comment by saudet** [comment]
A few other things:
1. Please get rid of the tabs and use spaces instead
2. There is a `return 0` that prevents the build from actually proceeding in `cppbuild.sh`
3. Could you use the files as downloaded in the `downloads` directory, the same as for the other platforms?

Then the native library builds, but "Nothing generated for C:\msys64\tmp\javacpp-presets\mxnet\target\classes\org\bytedeco\javacpp\jnimxnet.cpp". If I use the original presets then "LINK : fatal error LNK1181: cannot open input file 'mxnet.lib'", so there's still a bit to clean up, but once that's done, it looks like it's going to work, so it should be good to merge! Thanks

**Comment by Neiko2002** [comment]
I will have a look at it tomorrow. Downloading archives from the master branch might not be a good idea. Sometime MXNet is not stable, whats why I added the the stable commit part. They plan to release a new version 0.9 which we could use later on. Until then it might be better to git clone a stable commit for all operating systems.

**Comment by saudet** [comment]
Sure, please download those for other platforms as well, but do not use git: It doesn't always work well on Windows.

**Comment by saudet** [comment]
FYI, it's possible to download a specific commit if that was your question, for example:
https://github.com/dmlc/mxnet/archive/a5aeb0c43028f41863a8148eb3ecf30e90caad1e.tar.gz

**Comment by saudet** [comment]
FYI, I made some changes on the master branch that conflicts with your fork, so make sure to update it and resolve them!

**Comment by Neiko2002** [comment]
There should not be any conflicts. Github is blaming openblas.java because I've changed line 40 by adding "link = "libopenblas"," while you have changed line 39 to include the new blas_extrax.h

**Comment by saudet** [comment]
You could just reset and rebase your fork, that'll clear out everything for sure :)

**Comment by Neiko2002** [comment]
How do I reset a pull request? If I delete my remote fork Neiko2002/javacpp-presets nothing will happen to this pull request. 

I could not find any help here either:
https://help.github.com/categories/collaborating-with-issues-and-pull-requests/

**Comment by saudet** [comment]
Something like this: https://help.github.com/articles/syncing-a-fork/
But after fetching the upstream repo, we can also reset and rebase instead of merge...

**Comment by Neiko2002** [comment]
When I do all of this, I have a local branch with your changes first, followed by the changes of this PR. But my remote master [javacpp-presets](https://github.com/Neiko2002/javacpp-presets) is still the same. I can not reverse the changes of the remote master and therefore not the changes in this PR.

I've pushed the rebased and updated local branch to another remote branch:
https://github.com/Neiko2002/javacpp-presets/tree/mxnet

**Comment by saudet** [comment]
It's always possible to do `git reset` to whatever commit we wish.

**Comment by saudet** [comment]
`git merge` should work fine as well. Anyway, feel free to create another pull request if you prefer.

**Comment by saudet** [comment]
Hi, any news on this? The presets are now officially upgraded to Visual Studio 2015 as per #298, so this should go a lot more smoothly now. It would be great to have a build of MXNet for Windows!

In any case, I think it would be easiest to start a new PR from scratch. GitHub will probably do that anyway if we try to reset the branch.

Thanks for everything and let me know if you run into issues again. Thanks!

**Pull request merged**
