### PR TITLE
DepthAI (Android experimental) - Initialize with JavaVM function

### PR DESCRIPTION
**Pull request by themarpe**
Added an initialize function in depthai, which enables passing JavaVM pointer to underlying libusb library for Android usecase

### CODE REVIEW

**Comment by saudet** [comment]
Could you also update the files under src/gen to see what that looks like mapped to Java?

**Comment by themarpe** [comment]
Updated - will `initialize(Pointer javavm)` and `initialize(@StdString String additionalInfo)` or `initialize(@StdString BytePointer additionalInfo)` overload correctly when passing `initialize(Loader.getJavaVM())`? Otherwise there is still the full form, so not too much of an issue
```
@Namespace("dai") public static native @Cast("bool") boolean initialize();
@Namespace("dai") public static native @Cast("bool") boolean initialize(@StdString BytePointer additionalInfo, @Cast("bool") boolean installSignalHandler/*=true*/, Pointer javavm/*=nullptr*/);
@Namespace("dai") public static native @Cast("bool") boolean initialize(@StdString BytePointer additionalInfo);
@Namespace("dai") public static native @Cast("bool") boolean initialize(@StdString String additionalInfo, @Cast("bool") boolean installSignalHandler/*=true*/, Pointer javavm/*=nullptr*/);
@Namespace("dai") public static native @Cast("bool") boolean initialize(@StdString String additionalInfo);
@Namespace("dai") public static native @Cast("bool") boolean initialize(Pointer javavm);
```

**Comment by saudet** [comment]
Since `Loader.getJavaVM()` returns `Pointer` it can't match with any of the other overloads, so that looks alright, yes.

**Comment by themarpe** [comment]
Great - then I think this PR should work as intended:)

**Pull request merged**
