### PR TITLE
Support building OpenCV headless

### PR DESCRIPTION
**Pull request by harukizaemon**
Addresses #593: If the environment variable `HEADLESS=yes` then we will build OpenCV without QT, GTK, and WIN32UI.

### CODE REVIEW

**Comment by saudet** [comment]
Looks good, but unfortunately breaks the normal builds:
> ../cppbuild.sh: line 56: HEADLESS: unbound variable

https://travis-ci.org/bytedeco/javacpp-presets/jobs/477373066

**Comment by harukizaemon** [comment]
> Looks good, but unfortunately breaks the normal builds:

That's totally my bad. I only ran the OpenCV build so I didn't see the `set -eu`.

I have pushed another change that assigns default value of `no`. I'm sure there are other ways to handle this but I liked that this makes the default behaviour pretty clear.

**Comment by harukizaemon** [comment]
I noticed the AppVeyor build was cancelled. The Travis CI build now passes. Is there something else I need to do?

**Comment by saudet** [comment]
No, looks fine! Thanks

**Pull request merged**
