### PR TITLE
armhf MMAL accelerator

### PR DESCRIPTION
**Pull request by emilio1986**
MMAL video acceleration for Rassbery Pi 3 armhf processors

### CODE REVIEW

**Comment by saudet** [comment]
Great, thanks! @vb216 what do you think? Does it still work on old Raspberry Pi with software fallback?

**Comment by emilio1986** [comment]
Not sure. Tested only on RPI 3 :)

**Comment by vb216** [comment]
hopefully should get a chance this weekend to try on a pi zero as a test, tho not sure I call any MMAL stuff normally. is good to get optimisations like this in though!

**Comment by vb216** [comment]
@emilio1986 would you be able to send over a simple test case that uses the mmal functionality? I'd just like to give it a proper test, I dug out a pi1 to add to the test hardware now

**Comment by saudet** [comment]
BTW, does feature show up as an entirely separate codec? If so, then it probably does not interfere with the software codecs.

**Comment by saudet** [comment]
I'm trying to cross compile FFmpeg with MMAL, but it's looking for a file named `mmal.h` and it's not anywhere in https://github.com/raspberrypi/tools. Where can we find that file?

**Comment by saudet** [comment]
Ok, they are found in https://github.com/raspberrypi/userland. After executing `./buildme` and passing those paths to the configure scripts, I am able to build, but we get a dependency on `libmmal_core.so`, etc. Are those files present on almost all Raspberry Pis?

**Comment by vb216** [comment]
Looks like it lives here /opt/vc/lib/libmmal_core.so, that's on a recent raspbian distro - that usually covers alot of the userbase.

**Pull request merged**
