### PR TITLE
Update module-info.java

### PR DESCRIPTION
**Pull request by AKMANSoft**
helper package was missing in the file. Fix Error: module org.bytedeco.opencv does not export org.bytedeco.opencv.helper

### CODE REVIEW

**Comment by saudet** [comment]
@HGuillemet Let's append to this all other missing helper modules like that.

**Comment by HGuillemet** [comment]
I wrote a script to identify source directories without a corresponding export in module-info. It found:
```
org/bytedeco/cpython/helper
org/bytedeco/opencv/helper
org/bytedeco/qt/helper
```
and the following directories, which seems to have been introduced after the creation of the module-info:
```
org/bytedeco/llvm/program
org/bytedeco/tesseract/program
```
Do you think these 5 directories correspond to packages which must be exported (ie contain Java type that could be accessed by users) ?

**Comment by saudet** [comment]
Yes, they should be accessible. Thanks!

**Comment by HGuillemet** [comment]
@AKMANSoft, could you add to your PR these 5 exports to their corresponding module-info ?
I don't think I can do it myself without submitting another PR.
Thanks,

**Comment by AKMANSoft** [comment]
Yes no problem. I have added the exports.

**Pull request merged**
