### PR TITLE
Compile OpenCV on Linux-x86_64 with GTK

### PR DESCRIPTION
**Pull request by lloydmeta**
Not sure if this helps fix https://github.com/bytedeco/sbt-javacv/issues/14.

cc @RoiViber

### CODE REVIEW

**Comment by saudet** [comment]
It's already enabled. We need to figure out if it could be bundled somehow.

**Comment by lloydmeta** [comment]
Got it. Closing this then.

**Comment by RoiViber** [comment]
@lloydmeta I saw you committed a change to include GTK on compilation but how can I use the updated packaged jars? What version does this change apply to?

**Comment by lloydmeta** [comment]
@RoiViber currently sbt-javacv doesn't have an option to enable that easily, so you would need to add the GTK library into your build using the standard SBT means. Hope [this guide](http://www.scala-sbt.org/1.0/docs/Howto-Customizing-Paths.html#Include%2Fexclude+files+in+the+source+directory) helps.

**Comment by saudet** [comment]
@RoiViber Actually you would want to set that flag to OFF. The AWS machines are headless anyway.

**Comment by lloydmeta** [comment]
I think I understand what's going on now. Would it make sense to publish a `-headless` x86-64 preset then?

**Comment by saudet** [comment]
Maybe, but it might be easier to just bundle GTK...

**Comment by RoiViber** [comment]
@lloydmeta Sorry, I'm just back from a long vacation. I'm actually not familiar at all with GTK, so I don't know what you mean by bundle it. I've managed to talked to Amazon's support team, and installed GTK on my machines, but I'm still getting the following error:

> java.lang.UnsatisfiedLinkError: no jniopencv_videoio in java.library.path
>         at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
>         at java.lang.Runtime.loadLibrary0(Runtime.java:870)
>         at java.lang.System.loadLibrary(System.java:1122)
>         at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:804)
>         at org.bytedeco.javacpp.Loader.load(Loader.java:613)
>         at org.bytedeco.javacpp.Loader.load(Loader.java:530)
>         at org.bytedeco.javacpp.opencv_videoio.<clinit>(opencv_videoio.java:14)
>         at java.lang.Class.forName0(Native Method)
>         at java.lang.Class.forName(Class.java:348)
>         at org.bytedeco.javacpp.Loader.load(Loader.java:585)
>         at org.bytedeco.javacpp.Loader.load(Loader.java:530)
>         at org.bytedeco.javacpp.opencv_objdetect$CascadeClassifier.<clinit>(opencv_objdetect.java:585)
>         ....
> Caused by: java.lang.UnsatisfiedLinkError: /mnt/var/lib/hadoop-yarn/.javacpp/cache/mlageinf.jar/org/bytedeco/javacpp/linux-x86_64/libjniopencv_videoio.so: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
>         at java.lang.ClassLoader$NativeLibrary.load(Native Method)
>         at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
>         at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
>         at java.lang.Runtime.load0(Runtime.java:809)
>         at java.lang.System.load(System.java:1086)
>         at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:784)

Note that I'm actually running it on Spark, so that this might (finally) be a missing classpath issue?

**Comment by RoiViber** [comment]
I've just looked for this specific _libgtk-x11-2.0.so.0_ file and it appears it wasn't installed by Amazon's support team's suggestion:

> sudo yum --verbose -y --enablerepo=epel install gtk+-devel

but rather only the following files:

> /usr/lib64/libgdk-1.2.so.0
> /usr/lib64/libgdk-1.2.so.0.9.1
> /usr/lib64/libgtk-1.2.so.0
> /usr/lib64/libgtk-1.2.so.0.9.1

So it seems this is a version problem, that eventually is happening due to not-updated repo (?). From what repo did YOU take your GTK version?

**Comment by saudet** [comment]
Installing "gtk2-devel" should work then.

**Comment by salilotr89** [comment]
@RoiViber were you able to reach a solution for this problem? I am currently facing this same and would like to know what you did to get around it.

**Comment by saudet** [comment]
If you're talking about #349, then simply install GTK2.

**Pull request closed without merging**
