### PR TITLE
Accelerate BLAS

### PR DESCRIPTION
**Pull request by ibinti**
Address the issue #436

### CODE REVIEW

**Comment by ibinti** [comment]
Could you give me a hint how I can clean unrelated files?

**Comment by saudet** [comment]
What do you mean? Just remove them.

**Comment by saudet** [comment]
I see you're only mapping BLAS and LAPACK. Could you make this work with the presets for OpenBLAS instead?

**Comment by saudet** [comment]
BTW, I have a better idea on how to go about this. We should create a new generic presets for "netlib", which would be able to bind not only to Accelerate, OpenBLAS, or MKL but to others like AMD BLAS as well, in a fashion similar to the now defunct https://github.com/fommil/netlib-java project. Would you like to work on that?

**Comment by saudet** [comment]
I've made the necessary modifications in the commit above to be able to use Accelerate, etc with the bindings for OpenBLAS, so no need of separate presets for netlib for now. Instructions for Mac OS X at
https://github.com/bytedeco/javacpp-presets/tree/master/openblas#documentation

And thanks to @johanvos, when pull #515 gets merged, we should be able to do the same with iOS!

**Pull request closed without merging**
