### PR TITLE
Add windows-x86_64-gpu presets to tensorrt

### LINKED ISSUE #858: Can't build tensorrt on Windows x86_64
# bash cppbuild.sh -platform windows-x86_64 -extension "-gpu" install tensorrt
Detected platform "windows-x86_64"
Building for platform "windows-x86_64" with extension "-gpu"
Installing "tensorrt"
/d/javacpp/javacpp-presets/tensorrt/cppbuild /d/javacpp/javacpp-presets
Error: Platform "windows-x86_64" is not supported
/d/javacpp/javacpp-presets

How to build tensorrt for windows x86_64? I think tensorrt's headfile and interface are same on Windows and Linux.

### PR DESCRIPTION
**Pull request by StaticDefault**
Added TensorRT-7.0.0.11 for windows presets to tensorrt and appveyor code.
Added tensorrt download code in install-windows.sh file.

Fixes #858

### CODE REVIEW

**Comment by StaticDefault** [comment]
why build is failed?

**Comment by saudet** [comment]
It's just network problems, check the logs.

**Comment by StaticDefault** [comment]
ok, how can i help this problem? (i really want contribute javacpp project)

**Comment by saudet** [comment]
The build for TensorRT itself is probably fine. I'll merge this as soon as it's done. We don't need to worry about the other builds.

**Comment by StaticDefault** [comment]
thx for merge accept! i will contribute more.

**Pull request merged**
