### PR TITLE
Add macosx-arm64 preset for lz4

### PR DESCRIPTION
**Pull request by gab1one**
This PR enables the build of the macosx-arm64 preset for lz4.

Build is working, please let me know if anything else is missing.

(I created the PR with the wrong account earlier, that is why I closed that one and opened this one)

### CODE REVIEW

**Comment by saudet** [comment]
For consistency, everything "macosx-arm64" should appear before "macosx-x86_64", and we'll need to cross compile in cppbuild.sh, but the rest looks fine.

**Comment by gab1one** [comment]
- I added a commit to fix the ordering.
- Looking into setting the cross-compile settings

**Comment by saudet** [comment]
I don't think the target flag is going to work. Anyway, it's easier to use just "-arch arm64" and that's been working for all other builds, for example: https://github.com/bytedeco/javacpp-presets/blob/master/libffi/cppbuild.sh#L90

**Comment by gab1one** [comment]
Thanks for the tip, that seems to be working when running clang on mac.

**Comment by gab1one** [comment]
Is there anything else missing for this to get merged?

**Comment by gab1one** [comment]
Thank you very much for the support and merging 👍🏾

**Pull request merged**
