### PR TITLE
Updated caffe/cppbuild.sh to add Axpy layer to caffe

### PR DESCRIPTION
**Pull request by gunther82**
I added the Axpy layers to caffe cppbuild.sh

### CODE REVIEW

**Comment by saudet** [comment]
Thanks! Seems to be building just fine.

**Comment by saudet** [comment]
FYI, once Travis CI is done with https://travis-ci.org/bytedeco/javacpp-presets/builds/331203079 new JAR files that you can download will appear in https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/caffe/1.0-1.4.1-SNAPSHOT/

**Comment by gunther82** [comment]
Thanks for the compilation, now it works fine!
Just a questions, I'va seen in the repository that for linux there are 2 .jar files, one normal and one with gpu support. Is it possible to have the one with gpu support also for mac?

**Comment by saudet** [comment]
It might be possible, yes. Try to send a pull request with that build
enabled on Travis CI.

**Comment by saudet** [comment]
FYI, released with version 1.4.1. Thanks for the contribution!

**Pull request merged**
