### PR TITLE
Changes to support depthai in windows

### PR DESCRIPTION
**Pull request by mksbabu**

### CODE REVIEW

**Comment by mksbabu** [comment]
Hi @saudet

created pull request, could you please look into it, let me know please if any changes are required to support depthai in windows

pull request: https://github.com/bytedeco/javacpp-presets/pull/1430

Thanks.

**Comment by saudet** [comment]
You'll need to update the cppbuild.sh file as well:
https://github.com/bytedeco/javacpp-presets#build-instructions

**Comment by mksbabu** [comment]
@saudet updated version cppbuild.sh file. Is there anything need to change in that file since I am not aware on this project?

**Comment by saudet** [comment]
We'll need to do more than that: https://github.com/bytedeco/javacpp-presets/wiki/Create-New-Presets

**Comment by mksbabu** [comment]
Hi @saudet 

I am facing few build issues with this project when I imported in my local, not able to proceed further. If you don't mind, could you please make depthai to work in windows. I am thankful for your help.

Thanks.

**Comment by mksbabu** [comment]
It will be great help for our project if DepthAI to work with windows. Please consider my request.

Thanks,
Mks.

**Comment by saudet** [comment]
Like I keep telling you, contributions are welcome! I'm happy to help you get this working, but I don't have the time to do everything for everyone for free. If you're facing any problems, please let me know

**Comment by mksbabu** [comment]
Thanks for help!!
I have done few changes in cppbuild.sh to support for windows, Let me know please what else need to add to that file

**Comment by saudet** [comment]
You probably want to build for windows-x86_64, not windows-x86

**Comment by mksbabu** [comment]
I have added both windows-x86_64 and windows-x86(https://github.com/mksbabu/javacpp-presets-1/blob/master/depthai/cppbuild.sh), Let me know please if there is anything need to change

**Comment by saudet** [comment]
> 2023-10-31T09:51:06.1048629Z [ERROR] [ERROR] Could not find the selected project in the reactor: depthai @ 
> 2023-10-31T09:51:06.1049914Z [ERROR] Could not find the selected project in the reactor: depthai -> [Help 1]

That means we'll need to add depthai to the list here:
https://github.com/bytedeco/javacpp-presets/blob/master/pom.xml#L1647

**Comment by mksbabu** [comment]
@saudet I have updated pom.xml as per above comment from you, facing below error could you please let me know what's the resolution for below error
Error:  Failed to execute goal org.bytedeco:javacpp:1.5.9:build (javacpp-cppbuild-install) on project depthai: Execution javacpp-cppbuild-install of goal org.bytedeco:javacpp:1.5.9:build failed: Process exited with an error: 1 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.bytedeco:javacpp:1.5.9:build (javacpp-cppbuild-install) on project depthai: Execution javacpp-cppbuild-install of goal org.bytedeco:javacpp:1.5.9:build failed: Process exited with an error: 1

**Comment by mksbabu** [comment]
@saudet could you please help me to fix this pull request

**Comment by saudet** [comment]
The CMake build is failing on Windows, so you'll need to follow the instructions to build DepthAI on Windows, but I'm unable to find them. @themarpe Where can we find the build instructions for Windows?

**Comment by mksbabu** [comment]
@themarpe could you please help us on it

**Comment by mksbabu** [comment]
@saudet Is there any option to fix this issue. could you please help us on it.

**Comment by saudet** [comment]
Like I said before, I don't think DepthAI supports Windows, even though @themarpe says otherwise.

**Comment by saudet** [comment]
Have you considered using WSL2? It's usually possible to run any Linux applications on Windows that way.

**Comment by mksbabu** [comment]
I am not aware of it. could you please suggest what to do?

**Comment by saudet** [comment]
Duplicate of #1441

**Pull request closed without merging**
