### PR TITLE
initial work on ffmpeg 4.4.0

### PR DESCRIPTION
**Pull request by bradh**

### CODE REVIEW

**Comment by bradh** [comment]
Will try close/open cycling to restart the jobs.

**Comment by saudet** [comment]
Just let me know when you'd like to restart the jobs. I can do it manually without triggering events.

**Comment by saudet** [comment]
If you'd like to experiment some more, have more control, you can use GitHub Actions on your own fork as well.

**Review by supergrecko — COMMENTED** [review]
I'm not very familiar with the FFmpeg project, but I noticed some other minor things to update:

- The version number for FFmpeg should be updated everywhere. This means the following files should also have version numbers updated:
  - ffmpeg/platform/gpl/pom.xml
  - ffmpeg/platform/pom.xml
  - ffmpeg/README.md
  - README.md
- Commit the generated files under /src/gen/

**Comment by bradh** [comment]
@supergrecko Thanks for the suggestions. I've updated the version in each place I could find it, and added the generated files.

**Pull request merged**
