### PR TITLE
Add a linux-arm build for the OpenCV preset

### LINKED ISSUE #37: Raspberry Pi 2: Failed to execute JavaCPP Builder: Could not parse opencv2/core/types_c.h
Trying to build on a Raspberry Pi 2 yields the following error:

```
[ERROR] Failed to execute goal org.bytedeco:javacpp:0.10:build (generate-sources) on project opencv: Failed to execute JavaCPP Builder: Could not parse "opencv2/core/types_c.h": File does not exist -> [Help 1]
```

### PR DESCRIPTION
**Pull request by ThomasJClark**
This should make it possible to run JavaCV on non-android arm systems (probably including a Raspberry Pi, although I don't have one to try it on)

I've tested this on Fedora 23 using the ARM toolchains from lantw44/arm-linux-gnueabi-toolchain.  Basically it just adds a `linux-arm` option to `cppbuild.sh`. 

    ./cppbuild.sh -platform linux-arm install opencv
    mvn install --projects .,opencv -Dplatform=linux-arm -Dplatform.compiler=arm-linux-gnueabi-g++

Closes #37

### CODE REVIEW

**Comment by saudet** [comment]
Oh, if a cross-compiler works, that would be neat. Have you actually tested on any ARM devices?

**Comment by ThomasJClark** [comment]
@saudet I'm in the process of trying to get this tested on a [roboRIO](https://decibel.ni.com/content/docs/DOC-30419).  I have something compiled, but it'll be a little bit before I have physical access to the machine. I'll post an update then.

**Comment by saudet** [comment]
Cool. BTW, some people have been asking the same for FFmpeg. It doesn't look like it would be too hard to adapt it in the same way. Could you try it out and add it this PR if possible? :)

**Comment by JLLeitschuh** [comment]
:+1: (same [project](https://github.com/WPIRoboticsProjects/GRIP))

**Comment by saudet** [comment]
BTW, even if you don't get FFmpeg done, let me know when you confirm this works on roboRIO or what not, and I'll merge this PR in! Thanks

**Comment by ThomasJClark** [comment]
It works on the roboRIo, just with the ARM toolchains replaced with a roboRIO-specific one.

I don't know if I'm gonna get around to doing ffmpeg. Sorry.

**Comment by saudet** [comment]
Ok, thanks. It would be nice to hear about someone trying this out on Raspberry Pi at least though...

**Comment by saudet** [comment]
Well, anyway, I'll merge this in, and we'll let someone else test it out and let us know if it works. Thanks for the contribution!

**Pull request merged**
