### PR TITLE
Update tritonserver README and samples/pom.xml file

### PR DESCRIPTION
**Pull request by jbkyang-nvi**
Update Tritonserver README for instructions for local builds and updated pom.xml in samples to:
1. Allow only local builds
2. Remove need of generating Simple.java

### CODE REVIEW

**Comment by jbkyang-nvi** [comment]
@saudet we have 2 questions while creating this PR:
1. When we use the remote snapshots today(without this change), we found that 
`mvn compile exec:java -Djavacpp.platform=linux-x86_64`
will fail to compile with references to jar version `tensorrt 8.0`. It seems like the necessary SNAPSHOTS are correctly linked though. Is this a bug?
```
[ERROR] Failed to execute goal on project simple: Could not resolve dependencies for project org.bytedeco.tritonserver:simple:jar:1.5.7-SNAPSHOT: The following artifacts could not be resolved: org.bytedeco:tensorrt-platform:jar:8.0-1.5.7-SNAPSHOT, org.bytedeco:tensorrt:jar:8.0-1.5.7-SNAPSHOT: Could not find artifact org.bytedeco:tensorrt-platform:jar:8.0-1.5.7-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]
```

2. We have found that the local build will not work if we simply go to `javacpp-presets/tritonserver/samples` folder and run 
`mvn compile exec:java -Djavacpp.platform=linux-x86_64`. We have to run the commands for generating the JNI bindings _outside_ the `samples` folder like
```
 $ cd javacpp-presets
 $ mvn clean install --projects .,tritonserver
 $ mvn clean install -f platform --projects ../tritonserver/platform -Djavacpp.platform.host
```
Are the above commands necessary for compiling Simple.java? A bit confused since none of the other repos have READMEs where they highlight this step, nor do they add the requirement to add 
```
    <repositories>
        <repository>
            <id>sonatype-nexus-snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>
    </repositories>
```
to their POM.xml file

**Comment by saudet** [comment]
I've upgraded to TensorRT 8.2, so there's probably just some old versions of the pom.xml files left somewhere. Make sure to run `mvn -U ...`

**Comment by saudet** [comment]
If you're saying that you want to build everything locally though, you'll need to add commands to build the cuda and tensorrt modules as well. It's pretty much all documented in the README.md fille and on this wiki page:
https://github.com/bytedeco/javacpp-presets/#build-instructions
https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments
Let me know if there is anything unclear though.

**Comment by saudet** [comment]
If you're saying that you're OK with binaries compiled elsewhere, then yes we need to add the repository for snapshots, because there has not been any releases of the tritonserver module yet. Most users should be not using snapshots though, so that's why they do not appear in the README.md files or in the samples subdirectories, but the procedure is documented here for those who feel a bit more adventurous and are willing to help by testing new features: http://bytedeco.org/builds/

**Comment by jbkyang-nvi** [comment]
> I've upgraded to TensorRT 8.2, so there's probably just some old versions of the pom.xml files left somewhere. Make sure to run `mvn -U ...`

@saudet following the old set of commands I get:
```
$ mvn compile -U exec:java -Djavacpp.platform=linux-x86_64 -Dexec.args="-r /workspace/models"
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.914 s
[INFO] Finished at: 2022-01-18T04:37:45Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project simple: Could not resolve dependencies for project org.bytedeco.tritonserver:simple:jar:1.5.7-SNAPSHOT: The following artifacts could not be resolved: org.bytedeco:tensorrt-platform:jar:8.0-1.5.7-SNAPSHOT, org.bytedeco:tensorrt:jar:8.0-1.5.7-SNAPSHOT: Could not find artifact org.bytedeco:tensorrt-platform:jar:8.0-1.5.7-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]
```

Can you try to see if this happens for you as well?

**Comment by jbkyang-nvi** [comment]
> If you're saying that you want to build everything locally though, you'll need to add commands to build the cuda and tensorrt modules as well. It's pretty much all documented in the README.md fille and on this wiki page: https://github.com/bytedeco/javacpp-presets/#build-instructions https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments Let me know if there is anything unclear though.

The reason we haven't been able to build `cuda` or `tensorrt` in our docker container is because (not sure if Maven or the Builder) can't find `cuda.h`
```
$  mvn clean install -U --projects .,cuda,tensorrt -Djavacpp.platform=linux-x86_64
[INFO] bash /opt/tritonserver/javacpp-presets/cuda/../cppbuild.sh install cuda -platform=linux-x86_64 -extension=
Detected platform "linux-x86_64"
Building platform "linux-x86_64"
Installing "cuda"
/opt/tritonserver/javacpp-presets/cuda/cppbuild /opt/tritonserver/javacpp-presets
/opt/tritonserver/javacpp-presets
[INFO]
[INFO] --- build-helper-maven-plugin:3.3.0:add-source (add-source) @ cuda ---
[INFO] Source directory: /opt/tritonserver/javacpp-presets/cuda/src/gen/java added.
[INFO] Source directory: /opt/tritonserver/javacpp-presets/cuda/cppbuild/linux-x86_64/java added.
[INFO]
[INFO] --- maven-resources-plugin:3.1.0:resources (javacpp-parser) @ cuda ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /opt/tritonserver/javacpp-presets/cuda/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (javacpp-parser) @ cuda ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 26 source files to /opt/tritonserver/javacpp-presets/cuda/target/classes
[INFO]
[INFO] --- javacpp:1.5.7-SNAPSHOT:parse (javacpp-parser) @ cuda ---
[INFO] Detected platform "linux-x86_64"
[INFO] Building platform "linux-x86_64"
[INFO] Targeting /opt/tritonserver/javacpp-presets/cuda/src/gen/java/org/bytedeco/cuda/global/cublas.java
[ERROR] Failed to execute JavaCPP Builder: Could not parse "cuda.h": File does not exist
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] JavaCPP Presets 1.5.7-SNAPSHOT ..................... SUCCESS [  0.657 s]
[INFO] JavaCPP Presets for CUDA 11.6-8.3-1.5.7-SNAPSHOT ... FAILURE [  0.991 s]
[INFO] JavaCPP Presets for TensorRT 8.2-1.5.7-SNAPSHOT .... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.395 s
[INFO] Finished at: 2022-01-18T04:57:37Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.bytedeco:javacpp:1.5.7-SNAPSHOT:parse (javacpp-parser) on project cuda: Failed to execute JavaCPP Builder: Could not parse "cuda.h": File does not exist -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :cuda
```
even though 
```
$ find / -name cuda.h
/usr/include/linux/cuda.h
/usr/local/cuda-11.5/targets/x86_64-linux/include/cuda.h
/opt/hpcx/ompi/include/openmpi/opal/mca/hwloc/hwloc201/hwloc/include/hwloc/cuda.h
/workspace/server/python_backend/build/boost-src/src/boostorg/boost/predef/language/cuda.h
/workspace/server/python_backend/build/boost/predef/language/cuda.h
```
and the include path contains `/usr/include/linux`

Even stranger, when just building Tritonserver by itself does no have problems..
```
root@deae5f7f5539:/opt/tritonserver/javacpp-presets# mvn clean install -U --projects .,tritonserver -Djavacpp.platform=linux-x86_64
...
[INFO] --- javacpp:1.5.7-SNAPSHOT:parse (javacpp-parser) @ tritonserver ---
[INFO] Detected platform "linux-x86_64"
[INFO] Building platform "linux-x86_64"
[INFO] Targeting /opt/tritonserver/javacpp-presets/tritonserver/src/gen/java/org/bytedeco/tritonserver/global/tritonserver.java
[INFO] Parsing /usr/local/cuda-11.5/targets/x86_64-linux/include/cuda.h
```

**Comment by jbkyang-nvi** [comment]
> If you're saying that you're OK with binaries compiled elsewhere, then yes we need to add the repository for snapshots, because there has not been any releases of the tritonserver module yet. 
Not quite sure what you mean here. The Tritonserver binaries are compiled within the container, and we have JNI binary snapshots created for them in oss.sonatype right? However, when a user runs ` mvn compile -U exec:java -Djavacpp.platform=linux-x86_64` (in `javacpp-presets/tritonserver/samples`)  they get:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.791 s
[INFO] Finished at: 2022-01-18T05:24:59Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project simple: Could not resolve dependencies for project org.bytedeco.tritonserver:simple:jar:1.5.7-SNAPSHOT: Could not find artifact org.bytedeco:tritonserver-platform:jar:2.17-1.5.7-SNAPSHOT -> [Help 1]
```
That's why we have been using a local build of the Tritonserver JNI binary. The local build pulls from the CUDA snapshots and TensorRT snapshots(from oss.sonatype), and as a result our tests on the combined Tritonserver + Javacpp binaries work.

> Most users should be not using snapshots though, so that's why they do not appear in the README.md files or in the samples subdirectories, but the procedure is documented here for those who feel a bit more adventurous and are willing to help by testing new features: http://bytedeco.org/builds/

Do you mean that most users should be building everything locally, and not using any of the SNAPSHOTS at all?

**Comment by jbkyang-nvi** [comment]
@saudet do you think its reasonable to merge this PR as is? We can continue the conversation in this PR but our customer is super eager to try Tritonserver + Java... If there's any concerns please let me know!

**Comment by saudet** [comment]
> Can you try to see if this happens for you as well?

Hum, it looks like the pom.xml files here didn't get updated:
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/tritonserver/2.17-1.5.7-SNAPSHOT/
I've started a build for tritonserver, the snapshots should get updated in a bit:
https://github.com/bytedeco/javacpp-presets/actions/runs/1711250309

> ```
> /usr/local/cuda-11.5/targets/x86_64-linux/include/cuda.h
> ```

The presets have been upgraded to 11.6. You'll need to revert commit https://github.com/bytedeco/javacpp-presets/commit/fb6afbd36f2b819360c8b57b594b6c7a3f621b8e to get that going with 11.5.

> Even stranger, when just building Tritonserver by itself does no have problems..

As long as the binaries for CUDA are compatible enough, that can work, yes.

> Do you mean that most users should be building everything locally, and not using any of the SNAPSHOTS at all?

No, they should be using a release version, which is not available for tritonserver, yet. If you want to use the snapshots as releases in your containers, that's fine, but you should test those snapshots to make sure they work, and then create an uber JAR out of it, and distribute that with your releases, and not the original JAR files of the snapshots.

**Comment by saudet** [comment]
> @saudet do you think its reasonable to merge this PR as is? We can continue the conversation in this PR but our customer is super eager to try Tritonserver + Java... If there's any concerns please let me know!

You've removed the snapshot repository from the samples/pom.xml file. I think that's probably for the best, as it's going to prevent users from downloading random binaries and getting unstable versions, but is this what you want? It seemed like @jackyh really wanted it there.

**Comment by jbkyang-nvi** [comment]
> > @saudet do you think its reasonable to merge this PR as is? We can continue the conversation in this PR but our customer is super eager to try Tritonserver + Java... If there's any concerns please let me know!
> 
> You've removed the snapshot repository from the samples/pom.xml file. I think that's probably for the best, as it's going to prevent users from downloading random binaries and getting unstable versions, but is this what you want? It seemed like @jackyh really wanted it there.

The original reason we added the line is because without it, the build instructions didn't work. Didn't realize the problem was with SNAPSHOTS vs releases. We do want to create a uber jar with our release eventually. Two questions about this:
1. Does changing SNAPSHOTS to releases mean removing the `-SNAPSHOTS` suffix [here](https://github.com/bytedeco/javacpp-presets/blob/6af59ce1728a7526fe9b7c17e4ee53d017eafc37/tritonserver/pom.xml#L9) and [here](https://github.com/bytedeco/javacpp-presets/blob/6af59ce1728a7526fe9b7c17e4ee53d017eafc37/tritonserver/platform/pom.xml#L9)? Since we're giving the user a pre-release version I think it would be better to release everything as an uber jar with the Triton release itself. Do you see problems with the current local build of Tritonserver jar + pulling from release versions of CUDA and TensorRT? Do you foresee it being unstable from the users perspective? 
E.g, If you end up doing a 11.6 release for CUDA and TensorRT, that could create problems for the user if the installed CUDA is version 11.5, right?  

2. Do you have pointers of how to create a uber JAR? Right now with the current POM (in `samples` folder) we can create a `simple.jar` file, but it's not the uber jar we're looking for (and I assume it's not the uber jar you mentioned). 
 It looks like there are [Apache Maven Assembly Plugin](https://maven.apache.org/plugins/maven-assembly-plugin/index.html) and the [Maven Shade Plugin](https://maven.apache.org/plugins/maven-shade-plugin/usage.html). Do you have examples where you do it?


Thanks for patiently answering our questions by the way. We are slowly learning how to do the build & release process for Java projects with maven!

**Comment by jbkyang-nvi** [comment]
>> Can you try to see if this happens for you as well?

> Hum, it looks like the pom.xml files here didn't get updated:
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/tritonserver/2.17-1.5.7-SNAPSHOT/
I've started a build for tritonserver, the snapshots should get updated in a bit:
https://github.com/bytedeco/javacpp-presets/actions/runs/1711250309

Looks like the pom is updated this time!

**Comment by saudet** [comment]
> The original reason we added the line is because without it, the build instructions didn't work. Didn't realize the problem was with SNAPSHOTS vs releases. We do want to create a uber jar with our release eventually. Two questions about this:

Ok, so updating the build instructions is what you really wanted to solve issue #1122, got it, sounds good.

> 1. Does changing SNAPSHOTS to releases mean removing the `-SNAPSHOTS` suffix [here](https://github.com/bytedeco/javacpp-presets/blob/6af59ce1728a7526fe9b7c17e4ee53d017eafc37/tritonserver/pom.xml#L9) and [here](https://github.com/bytedeco/javacpp-presets/blob/6af59ce1728a7526fe9b7c17e4ee53d017eafc37/tritonserver/platform/pom.xml#L9)? Since we're giving the user a pre-release version I think it would be better to release everything as an uber jar with the Triton release itself. Do you see problems with the current local build of Tritonserver jar + pulling from release versions of CUDA and TensorRT? Do you foresee it being unstable from the users perspective?

Making a release involves deploying binaries in the permanent central repository here: https://search.maven.org/ 
The versions of those cannot end with "-SNAPSHOT", yes.

It's still OK to use the snapshot binaries for your releases though, but since the snapshots are not permanent, you can't rely on the snapshot repository to give you the same thing the next time you query it. You'll need to test the binaries you get, and keep them locally, in the form of an uber JAR is probably the easiest thing to do.

> E.g, If you end up doing a 11.6 release for CUDA and TensorRT, that could create problems for the user if the installed CUDA is version 11.5, right?

It might create problems, but as long as users don't try to use functions that are only available in 11.6, it should still work. But like I said, you'll need to test them to make sure.

> 2. Do you have pointers of how to create a uber JAR? Right now with the current POM (in `samples` folder) we can create a `simple.jar` file, but it's not the uber jar we're looking for (and I assume it's not the uber jar you mentioned).
>        It looks like there are [Apache Maven Assembly Plugin](https://maven.apache.org/plugins/maven-assembly-plugin/index.html) and the [Maven Shade Plugin](https://maven.apache.org/plugins/maven-shade-plugin/usage.html). Do you have examples where you do it?

Yes, that's correct, @jackyh already added maven-shade-plugin to tritonserver/samples/pom.xml in pull #1116, and I do get an uber JAR when executing `mvn clean package -Djavacpp.platform=linux-x86_64` on it:
```
-rw-rw-r--. 1 saudet saudet 8.4M Jan 19 11:11 simple-1.5.7-SNAPSHOT.jar
```
What do you get?

> Thanks for patiently answering our questions by the way. We are slowly learning how to do the build & release process for Java projects with maven!

You're welcome! It's a whole different ecosystem. I'm happy that NVIDIA is starting to take the time to look into it!

**Comment by jackyh** [comment]
@saudet Since we as a team need to prepare some without unstable snapshots. So, for now, could you just merge this PR for @jbkyang-nvi now?

**Comment by jbkyang-nvi** [comment]
> Yes, that's correct, @jackyh already added maven-shade-plugin to tritonserver/samples/pom.xml in pull #1116, and I do get an uber JAR when executing mvn clean package -Djavacpp.platform=linux-x86_64 on it

@saudet the issue is that we don't want an executable jar, but a non-executable library with which the user can call when compiling. Something like 
```
javac -cp javacpp-tritonserver.jar MyClass.java
java -cp .:javacpp-tritonserver.jar MyClass
```

**Comment by saudet** [comment]
> @saudet the issue is that we don't want an executable jar, but a non-executable library with which the user can call when compiling. Something like
> 
> ```
> javac -cp javacpp-tritonserver.jar MyClass.java
> java -cp .:javacpp-tritonserver.jar MyClass
> ```
> 
> This is because we don't want to require the user to use Maven, and have maximum flexibility on how they want to user the library

We can do that with the JAR that you can from samples/pom.xml, for example, this works just fine:
```bash
mv simple-1.5.7-SNAPSHOT.jar javacpp-tritonserver.jar
javac -cp javacpp-tritonserver.jar MyClass.java
java -cp .:javacpp-tritonserver.jar MyClass
```
The only thing that makes a JAR file "executable" is the mainClass entry that we're setting here:
https://github.com/bytedeco/javacpp-presets/blob/master/tritonserver/samples/pom.xml#L40
Just remove that line, and you'll get a "non-executable" uber JAR.

**Pull request merged**
