### PR TITLE
Add Windows support for LLVM

### LINKED ISSUE #305: Missing binary libraries for LLVM presets on Windows
When trying to run the [Fac](https://github.com/bytedeco/javacpp-presets/tree/master/llvm#sample-usage) example application on Windows 10, I am getting the error:

```
C:\bcc328\fac>mvn exec:java
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building fac 1.2
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.5.0:java (default-cli) @ fac ---
[WARNING]
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsatisfiedLinkError: no jniLLVM in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:654)
        at org.bytedeco.javacpp.Loader.load(Loader.java:492)
        at org.bytedeco.javacpp.Loader.load(Loader.java:409)
        at org.bytedeco.javacpp.LLVM.<clinit>(LLVM.java:10)
        at Fac.main(Fac.java:10)
        ... 6 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.953 s
[INFO] Finished at: 2016-10-18T07:20:46-02:00
[INFO] Final Memory: 9M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:java (default-cli) on project fac: An exception occured while executing the Java class. null: InvocationTargetException: no jniLLVM in java.library.path -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Basically there is `no jniLLVM in java.library.path`.

The same example works on Linux.

Inspecting the relevant jar file, no binary library can be found:

```
C:\bcc328\fac>"c:\Program Files\Java\jdk1.8.0_102\bin\jar" -tf \Users\romildo\.m2\repository\org\bytedeco\javacpp-preset
s\llvm\3.8.0-1.2\llvm-3.8.0-1.2-windows-x86_64.jar
META-INF/
META-INF/MANIFEST.MF
org/
org/bytedeco/
org/bytedeco/javacpp/
org/bytedeco/javacpp/windows-x86_64/
META-INF/maven/
META-INF/maven/org.bytedeco.javacpp-presets/
META-INF/maven/org.bytedeco.javacpp-presets/llvm/
META-INF/maven/org.bytedeco.javacpp-presets/llvm/pom.xml
META-INF/maven/org.bytedeco.javacpp-presets/llvm/pom.properties
```

Therefore it seems that the released version of `javacpp-presets` is missing the binary libraries needed to interface to LLVM on Windows.

### PR DESCRIPTION
**Pull request by delthas**
This adds Windows (x86 and x86_64) support for LLVM

This PR essentially updates #407 for LLVM 5.0.1. (It also fixes #305.)

### CODE REVIEW

**Comment by delthas** [comment]
@saudet I think this works now. (The latest commit Travis CI build fails but it's not related to LLVM.)

**Comment by saudet** [comment]
Thanks for the contribution! Let me know if the binaries in the snapshots don't look OK for some reason:
http://bytedeco.org/builds/

**Comment by mennodenhollander** [comment]
I tested the 5.0.1-1.4.1-SNAPSHOT version. The windows dependencies are missing from the llvm-platform-5.0.1-1.4.1-SNAPSHOT.pom. To get it to work I had to explicitly add the windows dependency to my project:

```
<dependency>
    <groupId>org.bytedeco.javacpp-presets</groupId>
    <artifactId>llvm</artifactId>
    <version>5.0.1-1.4.1-SNAPSHOT</version>
    <classifier>windows-x86_64</classifier>
</dependency>
```

**Comment by saudet** [comment]
Yes, indeed, please send a pull request!

**Pull request merged**
