### PR TITLE
Windows support for the mxnet preset (issue #234)

### PR DESCRIPTION
**Pull request by Neiko2002**

### CODE REVIEW

**Comment by saudet** [comment]
Could you make it so that it builds from source? 
Using existing binaries causes problems we can't fix: https://github.com/bytedeco/javacpp-presets/issues/225

**Comment by Neiko2002** [comment]
It is possible, but on a normal windows system you don't have OpenBLAS installed and added to your PATH. Which means we would need to include it (plus its dependencies libgcc_s_seh-1.dll, libgfortran-3.dll, libquadmath-0.dll) to the resulting .jar file. Increasing the size by about 40MB. 

For windows it would be good to use the existing/installed libraries and warn the user it they are not configured correctly.

**Comment by saudet** [comment]
OpenBLAS comes with MSYS2. Just call 
```
pacman -S mingw-w64-x86_64-openblas mingw-w64-i686-openblas`
```

**Comment by saudet** [comment]
And if we them to the `link` or `preload` value of the `@Platform` annotation, the build process of JavaCPP will bundle them in the JAR file, so no library needs to be available at runtime on the machine.

**Comment by saudet** [comment]
But it shouldn't increase the size by more than 10 megs though. Where do you get 40 megs from?

**Comment by Neiko2002** [comment]
I have installed the OpenBLAS binary and the libopenblas.dll inside is 38MB.
https://sourceforge.net/projects/openblas/files/v0.2.14/

Getting OpenBLAS via MSYS2 downloads a 33MB libopenblas.dll. If we bundle all the necessary binaries together it will result in a >40MB MXNet jar file. We will need OpenBLAS for other libraries as well, so I was thinking that there might be another way to distribute the 3rd party libraries.

**Comment by saudet** [comment]
Right, but compressed it's more like 5 megs:
http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-openblas-0.2.17-1-any.pkg.tar.xz

**Comment by saudet** [comment]
Sure, we could make presets for OpenBLAS. After all, it gets used by Caffe, ND4J, and probably others as well. BLAS is an API implemented by other libraries though, so we might want to figure out how to make binaries compatible with MKL as well: https://github.com/bytedeco/javacpp-presets/issues/112

**Comment by saudet** [comment]
Build instructions for Windows are available here:
https://github.com/dmlc/mxnet/blob/master/docs/how_to/build.md#building-on-windows
Could you translate that into a bash script? That's what I'd like to add to the cppbuild.sh script.

**Comment by Neiko2002** [comment]
The next 2-3 weeks are full or work, but I think within the next month it should be ready.

**Comment by saudet** [comment]
Duplicate of #309. Please don't create duplicate pull requests. Simply update the pull request next time!! Thank you

**Pull request closed without merging**
