### PR TITLE
Introduce `linux-arm64` to presets for libpostal

### PR DESCRIPTION
**Pull request by MasseGuillaume**

### CODE REVIEW

**Comment by saudet** [comment]
Looks good, but please fix the builds on GitHub Actions! Also, there's a couple of missing entries in platform/pom.xml.

**Comment by MasseGuillaume** [comment]
Hi, sorry for the delay I was on vacation. It looks like the failure was related to some changes in GitHub unrelated to this PR:

Downloading https://github.com/openvenues/libpostal/archive/v1.1.tar.gz gives the following error:

> the given path has multiple possibilities: #<Git::Ref:0x00007fd6613eefb0>, #<Git::Ref:0x00007fd6613ee8d0>

I fixed the URL by adding refs tags to remove the ambiguity. I will need your approval to re-run the Github actions.

**Comment by saudet** [comment]
https://github.com/openvenues/libpostal/archive/refs/tags/v1.1.tar.gz seems to be working correctly. Let's use that?

**Comment by MasseGuillaume** [comment]
Yup that's the fix I'm trying right now.
https://github.com/bytedeco/javacpp-presets/pull/1199/commits/aff629473de97ca41b3476d56d566f70d57863b8#diff-ae4eed1b337db40a14189f50b893c841de813757ab17c9f41e6d903263ab6f86R11

**Comment by MasseGuillaume** [comment]
Hum something is off

```
[INFO] Detected platform "linux-x86_64"
[INFO] Building platform "linux-arm64"
```

I think it might be related to the missing `manifestEntry` in the pom file. I added the change and pushed here:

https://github.com/bytedeco/javacpp-presets/pull/1199/commits/00d4297477baedeb1453fe37bf8901a3d34c46ca#diff-95113202bf744a6965dfbcb1a37d7690d52ae6258cabed7bb1e5245921450e63

**Comment by saudet** [comment]
> Hum something is off
> 
> ```
> [INFO] Detected platform "linux-x86_64"
> [INFO] Building platform "linux-arm64"
> ```
> 
> I think it might be related to the missing `manifestEntry` in the pom file. I added the change and pushed here:

No, that's alright. GitHub Actions doesn't have ARM runners, yet, so we need to cross compile.

**Comment by MasseGuillaume** [comment]
Ah ok I understand now, I added the cross-compilation flag: `--host=aarch64-linux-gnu` to `./configure`:

https://github.com/bytedeco/javacpp-presets/pull/1199/files#diff-ae4eed1b337db40a14189f50b893c841de813757ab17c9f41e6d903263ab6f86R38

If you can allow the CI to run, I think this time it should work.

**Comment by MasseGuillaume** [comment]
Great, it looks like we now have a linux-arm64 libpostal: https://github.com/MasseGuillaume/javacpp-presets/runs/7520138130

**Comment by MasseGuillaume** [comment]
I think this PR is all good for a merge, did I miss anything?

**Pull request merged**
