### PR TITLE
Fixed LAPACK support for OpenBLAS in Android.

### PR DESCRIPTION
**Pull request by jadarve**
Patch to support LAPACK in Android as discussed in https://github.com/bytedeco/javacpp-presets/issues/402

These changes require to modify the Android NDK and replace the x86 and arm7 toolchains with those provided in https://github.com/buffer51/android-gfortran/releases

### CODE REVIEW

**Comment by saudet** [comment]
Thanks! Could you move the build instructions to the wiki page for that though?
https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments#android-arm-and-x86

**Comment by jadarve** [comment]
I moved the instructions to the wiki page.

**Comment by saudet** [comment]
Thanks! Have you verified that all other presets also build fine with that
installed? We'll need to confirm that...

**Comment by jadarve** [comment]
Oh, actually I have not verified if the other presets build with the modified toolchain. I will try and let you know.

**Comment by saudet** [comment]
We now have Travis CI working thanks to @vb216. Could you make those toolchain adjustments in the build script at https://github.com/bytedeco/javacpp-presets/blob/master/ci/install-travis.sh#L127 ? We'll then be able to see easily that everything builds fine with those changes and finally merge this! Thanks a lot

**Comment by jadarve** [comment]
I am not aware of any alternative.

**Comment by duanshanchong** [comment]
I have also encountered this problem. Have you solved it？

**Comment by saudet** [comment]
I've upgraded the presets for OpenBLAS 0.3.21 (see commit https://github.com/bytedeco/javacpp-presets/commit/7d9084fcb16404c35c0b144b541960eeafa7fcf8), which no longer requires a Fortran compiler to build LAPACK, so it's now available for all platforms, including Android, iOS, and Mac on ARM, so I think we can close this pull request. Please give it a try with the snapshots: http://bytedeco.org/builds/ Let me know if you encounter any issues with them though! Thank you

**Pull request closed without merging**
