### PR TITLE
LLVM on ARM64

### PR DESCRIPTION
**Pull request by loicottet**
I'd need to have the ARM64 binaries included in the org.bytedeco:llvm releases. For now I have managed to compile them locally with these changes, is there a CI I should pass to check it?

### CODE REVIEW

**Comment by saudet** [comment]
Yes, please try to add it to the .travis.yml file.

**Comment by saudet** [comment]
Hum, looks like we'll need to do a bit more to get cross-compilation working for LLVM:
https://llvm.org/docs/HowToCrossCompileLLVM.html

**Comment by saudet** [comment]
@vb216 Would you like to help with that? It looks like it would work for linux-armhf as well, so we can start there...

**Comment by vb216** [comment]
Looks an interesting one, but too many other commitments on at the moment to offer much help right now

**Comment by loicottet** [comment]
Great! Thanks a lot!

**Comment by saudet** [comment]
@loicottet BTW, I see that you've been using these bindings to implement an LLVM backend for Graal's Substrate VM. That's really great! I'm happy to see that JavaCPP is useful for the GraalVM project. If you think of anything else that I can do to help with this or anything else, please let me know!

**Comment by loicottet** [comment]
@saudet The JavaCPP bindings have definitely been a great help in this project! Being able to target ARM is a big milestone for us and we'll probably need your help when targeting new architectures in the future, I'll let you know!

**Pull request merged**
