### PR TITLE
Add windows-x86_64 build to liquidfun

### LINKED ISSUE #524: liquidfun Preset doesn't work on Windows x64
I've set up a gradle project with liquidfun javacpp preset, and when I run it the following exception appears:

> Exception in thread "main" java.lang.UnsatisfiedLinkError: Platform "windows-x86_64" not supported by class org.bytedeco.javacpp.liquidfun
	at org.bytedeco.javacpp.Loader.load(Loader.java:891)
	at org.bytedeco.javacpp.Loader.load(Loader.java:854)
	at org.bytedeco.javacpp.liquidfun.<clinit>(liquidfun.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at org.bytedeco.javacpp.Loader.load(Loader.java:913)
	at org.bytedeco.javacpp.Loader.load(Loader.java:854)

What could be the problem?

### PR DESCRIPTION
**Pull request by nornagon**
Fixes #524

### CODE REVIEW

**Comment by nornagon** [comment]
Haven't tested this at all, just trying the obvious thing and letting appveyor do the heavy lifting :)

**Comment by saudet** [comment]
We'll need to add it to the `.appveyor.yml` file though if we want this to be tested by AppVeyor though...

**Comment by nornagon** [comment]
lol, whoops. Fixed, hopefully!

**Comment by saudet** [comment]
BTW, we can speed up the process by temporarily commenting out all other builds from `.appveyor.yml` and `.travis.yml`.

**Comment by saudet** [comment]
BTW2, it is also possible to access the build machine with RDP:
https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
As client http://www.rdesktop.org/ works fine for me on Linux.

**Pull request merged**
