### PR TITLE
tensorflow: bind DotGraph

### PR DESCRIPTION
**Pull request by Mistobaan**
This is a first attempt at getting more familiar with javacpp and the tensorflow bindings. Not sure if is the best way to map this simple func + struct, but it compiles and works .

### CODE REVIEW

**Comment by saudet** [comment]
Yes, I think that's pretty much the best we can do. Good job!

The ordering and formatting of the new code could be a bit more consistent with the existing code, but it's not a big deal.

Let me know if you intend to work more on this or not! Thanks

**Comment by Mistobaan** [comment]
sure I can fix the formatting. Is there a defined format for the project that I can just run and auto formats it ? (like `go fmt`).

I am not able to "subclass" those Function Pointers to actually implement a Java-struct to pass to inside the C++ Dot function. Even adding `@Virtual` in the code. Maybe I am doing it wrong. How would you subclass it properly ?

**Comment by saudet** [comment]
No, don't have a formatter for that. Like I said, it's still alright the way it is now :)

When you say you can't subclass them, what problems are you encountering? Simply overriding a `call()` method and letting it use the protected constructor should work. What is the expected behavior vs the observed one?

**Comment by saudet** [comment]
In any case, it builds fine for me, so let's merge this in. If you still have problems getting callbacks to work, let me know! Thanks

**Pull request merged**
