### PR TITLE
[FFmpeg] Add --enable-libpulse

### LINKED ISSUE #1471: FFMpeg does not work with PulseAudio
`av_find_input_format("pulse")` returns null, whereas `ffmpeg -f pulse ...` using the system build of ffmpeg works completely fine. I've tried both the regular and the GPL builds.

```
ffmpeg version n6.1.1 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13.2.1 (GCC) 20230801
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-frei0r --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libharfbuzz --enable-libiec61883 --enable-libjack --enable-libjxl --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libplacebo --enable-libpulse --enable-librav1e --enable-librsvg --enable-librubberband --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpl --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-opencl --enable-opengl --enable-shared --enable-vapoursynth --enable-version3 --enable-vulkan
```

From this output, I'm assuming the javacpp build is simply missing the "--enable-libpulse" flag.

### PR DESCRIPTION
**Pull request by Martmists-GH**
Fixes #1471

### CODE REVIEW

**Comment by Martmists-GH** [comment]
Not sure why tests are failing, seems to be unrelated to my code.

@saudet How long does it usually take for PRs to get merged?

**Comment by saudet** [comment]
The builds are failing. That needs to be fixed

**Comment by Martmists-GH** [comment]
I'm not sure how, it seems to be failing on packages and I didn't touch those

**Comment by saudet** [comment]
```
2024-02-16T14:50:25.4392008Z require_pkg_config libpulse libpulse pulse/pulseaudio.h pa_context_new
2024-02-16T14:50:25.4392242Z check_pkg_config libpulse libpulse pulse/pulseaudio.h pa_context_new
2024-02-16T14:50:25.4392495Z test_pkg_config libpulse libpulse pulse/pulseaudio.h pa_context_new
2024-02-16T14:50:25.4392652Z false --exists --print-errors libpulse
2024-02-16T14:50:25.4392825Z ERROR: libpulse not found using pkg-config
2024-02-16T14:50:25.4393082Z Makefile:186: /tests/Makefile: No such file or directory
2024-02-16T14:50:25.4393312Z make: *** No rule to make target '/tests/Makefile'.  Stop.
```

**Comment by streamingdv** [comment]
@Martmists-GH just a hint, you enabled libpulse in ffmpeg so you must guarantee that the required libs and headers are available on all build systems (android, linux, mac, windows). This seems not to be the case so all ffmpeg builds are failing

**Comment by Martmists-GH** [comment]
What should I do then? I can build ffmpeg just fine on my PC

**Comment by streamingdv** [comment]
As you can see the builds are failing clearly because of your changes (look at the answer of saudet). If you want to include a new feature like libpulse you must guarantee that the ffmpeg builds will pass for all available platforms, not just one. If it works on your PC the ffmpeg build is able to detect necessary dependencies and libs to build it with libpulse enabled but as you can see that's not the case for the build systems of javacpp-presets. In the .github/actions folder you have the individual setups for each build system (deploy-ubuntu, deploy-windows...) which you need to configure appropriately for building ffmpeg with libpulse support.

**Comment by Martmists-GH** [comment]
@streamingdv I'm not quite sure why this is failing, I installed libpuslse-dev but pkg-config seems to still fail to find it? I'm not familiar with ubuntu but I can gather online this *should* work

**Review by saudet — APPROVED** [review]

**Pull request merged**
