### PR TITLE
Addition of libpostal preset

### PR DESCRIPTION
**Pull request by Maurice-Betzel**
Requesting addition of the libpostal preset for Windows, Linux and MacOS 64bit.
libpostal is a C library for parsing/normalizing street addresses around the world using statistical NLP and open data. The goal of this project is to understand location-based strings in every language, everywhere.

### CODE REVIEW

**Comment by saudet** [comment]
Thanks! Please also add to `.travis.yml` and `.appveyor.yml` and let's see if it builds fine on all platforms.

**Comment by saudet** [comment]
Thanks! Could you also add entries for unsupported platforms to make sure empty artifacts get created?

**Comment by saudet** [comment]
Yeah, unfortunately Maven, etc require empty artifacts for unsupported platforms, or users have to exclude them manually.

**Comment by Maurice-Betzel** [comment]
Now the unsupported platform builds are failing because of the missing libpostal header file that JavaCPP is expecting. How to solve this?

**Comment by saudet** [comment]
List only the supported platforms in the `@Platform(value = ...` annotation value.

**Comment by Maurice-Betzel** [comment]
Keep your fingers crossed, and i wish you a happy and health new year :)

**Comment by Maurice-Betzel** [comment]
Since libpostal is written in c and the header file declares `#ifdef __cplusplus extern "C" {...`, do i need to use cinclude instead of include in the annotations declaration?

**Comment by saudet** [comment]
It doesn't look like it, but it's usually preferable yes.

**Comment by Maurice-Betzel** [comment]
GCC has  no cpp 11 for Linux x86_64? LLVM seems to have it, what am i missing/overseeing?

**Comment by Maurice-Betzel** [comment]
Samuel, i see you have removed the need for empty artefacts. If the builds run fine now I will commit the resolved conflicts.

**Comment by saudet** [comment]
Yes, please do. Sorry for the breaking changes, but you had me started thinking about this and it clicked so I made the changes. :) And while you're at it, version "1.1-alpha" was just released, so let's use that for the presets: https://github.com/openvenues/libpostal/releases 

As for C++11 support with GCC or Clang, we need to pass them an option, and we can do that with a `@Platform(compiler="cpp11", ...` annotation.

**Comment by Maurice-Betzel** [comment]
I just removed the cpp 11 directive because the linux build failed on travis because of it and i cannot trace why. I will try the alpha version locally, yesterday morning the build was breaking untill the latest commits of albarrentine.

**Comment by Maurice-Betzel** [comment]
Having following issues with v1.1-alpha executing JavaCPP:

[INFO] --- javacpp:1.3.4-SNAPSHOT:build (javacpp.compiler) @ libpostal ---
[INFO] Detected platform "windows-x86_64"
[INFO] Building for platform "windows-x86_64"
[INFO] Generating C:\msys64\home\betzm\javacpp-presets\libpostal\target\classes\org\bytedeco\javacpp\jnijavacpp.cpp
[INFO] Generating C:\msys64\home\betzm\javacpp-presets\libpostal\target\classes\org\bytedeco\javacpp\jnilibpostal.cpp
[INFO] Compiling C:\msys64\home\betzm\javacpp-presets\libpostal\target\classes\org\bytedeco\javacpp\windows-x86_64\jnilibpostal.dll
[INFO] cl /IC:\msys64\home\betzm\javacpp-presets\libpostal/cppbuild/windows-x86_64/include/ /IC:\Users\betzm\Development\jdk\jdk1.8.0_144\include /IC:\Users\betzm\Development\jdk\jdk1.8.0_144\include\win32 C:\msys64\home\betzm\javacpp-presets\libpostal\target\classes\org\bytedeco\javacpp\jnilibpostal.cpp C:\msys64\home\betzm\javacpp-presets\libpostal\target\classes\org\bytedeco\javacpp\jnijavacpp.cpp /Oi /O2 /EHsc /Gy /GL /MD /LD /W3 /link /OUT:jnilibpostal.dll /LIBPATH:C:\msys64\home\betzm\javacpp-presets\libpostal/cppbuild/windows-x86_64/lib/ libpostal.lib psapi.lib 
Microsoft (R) C/C++ Optimizing Compiler Version 19.12.25830.2 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

jnilibpostal.cpp
C:\msys64\home\betzm\javacpp-presets\libpostal\target\classes\org\bytedeco\javacpp\jnilibpostal.cpp(241): warning C4267: 'argument': conversion from 'size_t' to 'jsize', possible loss of data
C:\msys64\home\betzm\javacpp-presets\libpostal\target\classes\org\bytedeco\javacpp\jnilibpostal.cpp(242): warning C4267: 'argument': conversion from 'size_t' to 'jsize', possible loss of data
C:\msys64\home\betzm\javacpp-presets\libpostal\target\classes\org\bytedeco\javacpp\jnilibpostal.cpp(283): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt\string.h(132): note: see declaration of 'strcpy'
C:\msys64\home\betzm\javacpp-presets\libpostal\target\classes\org\bytedeco\javacpp\jnilibpostal.cpp(285): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt\string.h(337): note: see declaration of 'strncpy'
jnijavacpp.cpp
C:\msys64\home\betzm\javacpp-presets\libpostal\target\classes\org\bytedeco\javacpp\jnijavacpp.cpp(501): warning C4267: 'argument': conversion from 'size_t' to 'jsize', possible loss of data
C:\msys64\home\betzm\javacpp-presets\libpostal\target\classes\org\bytedeco\javacpp\jnijavacpp.cpp(502): warning C4267: 'argument': conversion from 'size_t' to 'jsize', possible loss of data
C:\msys64\home\betzm\javacpp-presets\libpostal\target\classes\org\bytedeco\javacpp\jnijavacpp.cpp(543): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt\string.h(132): note: see declaration of 'strcpy'
C:\msys64\home\betzm\javacpp-presets\libpostal\target\classes\org\bytedeco\javacpp\jnijavacpp.cpp(545): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt\string.h(337): note: see declaration of 'strncpy'
C:\msys64\home\betzm\javacpp-presets\libpostal\target\classes\org\bytedeco\javacpp\jnijavacpp.cpp(1167): warning C4996: 'strcat': This function or variable may be unsafe. Consider using strcat_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt\string.h(89): note: see declaration of 'strcat'
C:\msys64\home\betzm\javacpp-presets\libpostal\target\classes\org\bytedeco\javacpp\jnijavacpp.cpp(1230): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt\string.h(337): note: see declaration of 'strncpy'
C:\msys64\home\betzm\javacpp-presets\libpostal\target\classes\org\bytedeco\javacpp\jnijavacpp.cpp(1252): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt\string.h(132): note: see declaration of 'strcpy'
C:\msys64\home\betzm\javacpp-presets\libpostal\target\classes\org\bytedeco\javacpp\jnijavacpp.cpp(1310): warning C4996: 'strncat': This function or variable may be unsafe. Consider using strncat_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt\string.h(265): note: see declaration of 'strncat'
C:\msys64\home\betzm\javacpp-presets\libpostal\target\classes\org\bytedeco\javacpp\jnijavacpp.cpp(1362): warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt\string.h(181): note: see declaration of 'strerror'
C:\msys64\home\betzm\javacpp-presets\libpostal\target\classes\org\bytedeco\javacpp\jnijavacpp.cpp(1448): warning C4996: 'strtok': This function or variable may be unsafe. Consider using strtok_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt\string.h(439): note: see declaration of 'strtok'
Microsoft (R) Incremental Linker Version 14.12.25830.2
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:jnilibpostal.dll 
/ltcg 
/dll 
/implib:jnilibpostal.lib 
/OUT:jnilibpostal.dll 
/LIBPATH:C:\msys64\home\betzm\javacpp-presets\libpostal/cppbuild/windows-x86_64/lib/ 
libpostal.lib 
psapi.lib 
jnilibpostal.obj 
jnijavacpp.obj 
   Creating library jnilibpostal.lib and object jnilibpostal.exp
jnilibpostal.obj : error LNK2001: unresolved external symbol __imp_libpostal_is_toponym_duplicate
jnilibpostal.obj : error LNK2001: unresolved external symbol __imp_libpostal_is_street_duplicate_fuzzy
jnilibpostal.obj : error LNK2001: unresolved external symbol __imp_libpostal_is_house_number_duplicate
jnilibpostal.obj : error LNK2001: unresolved external symbol __imp_libpostal_get_duplicate_options_with_languages
jnilibpostal.obj : error LNK2001: unresolved external symbol __imp_libpostal_get_default_duplicate_options
jnilibpostal.obj : error LNK2001: unresolved external symbol __imp_libpostal_near_dupe_hashes
jnilibpostal.obj : error LNK2001: unresolved external symbol __imp_libpostal_is_floor_duplicate
jnilibpostal.obj : error LNK2001: unresolved external symbol __imp_libpostal_is_po_box_duplicate
jnilibpostal.obj : error LNK2001: unresolved external symbol __imp_libpostal_get_default_fuzzy_duplicate_options
jnilibpostal.obj : error LNK2001: unresolved external symbol __imp_libpostal_place_languages
jnilibpostal.obj : error LNK2001: unresolved external symbol __imp_libpostal_is_name_duplicate
jnilibpostal.obj : error LNK2001: unresolved external symbol __imp_libpostal_is_postal_code_duplicate
jnilibpostal.obj : error LNK2001: unresolved external symbol __imp_libpostal_is_unit_duplicate
jnilibpostal.obj : error LNK2001: unresolved external symbol __imp_libpostal_tokenize
jnilibpostal.obj : error LNK2001: unresolved external symbol __imp_libpostal_near_dupe_hashes_languages
jnilibpostal.obj : error LNK2001: unresolved external symbol __imp_libpostal_normalize_string
jnilibpostal.obj : error LNK2001: unresolved external symbol __imp_libpostal_get_default_fuzzy_duplicate_options_with_languages
jnilibpostal.obj : error LNK2001: unresolved external symbol __imp_libpostal_get_near_dupe_hash_default_options
jnilibpostal.obj : error LNK2001: unresolved external symbol __imp_libpostal_is_street_duplicate
jnilibpostal.obj : error LNK2001: unresolved external symbol __imp_libpostal_is_name_duplicate_fuzzy
jnilibpostal.obj : error LNK2001: unresolved external symbol __imp_libpostal_expand_address_root
jnilibpostal.obj : error LNK2001: unresolved external symbol libpostal_normalized_tokens
jnilibpostal.dll : fatal error LNK1120: 22 unresolved externals
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

**Comment by saudet** [comment]
Meh, if we can't use releases, let's create versions with the date and the hash, as with LiquidFun, for example: https://github.com/bytedeco/javacpp-presets/pull/356#issuecomment-277405116

**Comment by Maurice-Betzel** [comment]
OK, will do.

**Comment by Maurice-Betzel** [comment]
So far so good, is there anything more i can do?

**Comment by saudet** [comment]
Yes, looks good, thanks! So, let's see, two last things. Could you use `./configure --prefix` instead of manually copying the files? Also, since we are building libpostal with GCC, let's also use GCC to compile the wrappers. We don't need to use `lib.exe` to get a .lib file too. libdc1394 does both so we can use the cppbuild.sh and pom.xml file as reference:
https://github.com/bytedeco/javacpp-presets/tree/master/libdc1394

**Comment by Maurice-Betzel** [comment]
JavaCPP is missing the libpostal.h header file, even with this setup:

windows-x86_64)
    cp -rf windows/* ./
    INSTALL_PATH=$(pwd)
    bash -lc "cd $INSTALL_PATH && ./bootstrap.sh"
    CC="gcc -m64 -Duint=int -static-libgcc"
    mkdir -p "$INSTALL_PATH/src/.libs"
    export LIBRARY_PATH="$INSTALL_PATH/src/.libs/"
    export C_INCLUDE_PATH="$INSTALL_PATH/src/"
    bash -lc "cd $INSTALL_PATH && ./configure --disable-data-download --prefix=$LIBRARY_PATH"
    bash -lc "cd $INSTALL_PATH && make -j4"
    bash -lc "cd $INSTALL_PATH && make install"

The C_INCLUDE_PATH seems not to be working.

**Comment by Maurice-Betzel** [comment]
Ok, i am getting the hang of this :)
But i am missing the lib file

windows-x86_64)
    cp -rf windows/* ./
    SOURCE_PATH=$(pwd)
    bash -lc "cd $SOURCE_PATH && ./bootstrap.sh"
    CC="gcc -m64 -Duint=int -static-libgcc"
    bash -lc "cd $SOURCE_PATH && ./configure --disable-data-download --prefix=$INSTALL_PATH"
    #bash -lc "cd $SOURCE_PATH && ./configure --disable-data-download --prefix=$INSTALL_PATH --datadir=/c/[...some dir with a few GB of space...]"
    bash -lc "cd $SOURCE_PATH && make -j4"
    bash -lc "cd $SOURCE_PATH && make install"

Microsoft (R) Incremental Linker Version 14.12.25830.2
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:jnilibpostal.dll 
/ltcg 
/dll 
/implib:jnilibpostal.lib 
/OUT:jnilibpostal.dll 
/LIBPATH:C:\msys64\home\betzm\javacpp-presets\libpostal/cppbuild/windows-x86_64/lib/ 
libpostal.lib 
psapi.lib 
jnilibpostal.obj 
jnijavacpp.obj 
LINK : fatal error LNK1181: cannot open input file 'libpostal.lib'
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 08:26 min
[INFO] Finished at: 2018-01-07T17:28:56+01:00
[INFO] Final Memory: 22M/251M
[INFO] ------------------------------------------------------------------------

**Comment by saudet** [comment]
Modify the pom.xml file to use GCC there as well.

**Comment by Maurice-Betzel** [comment]
The pom is equal to libdc1394, how can i configure JavaCPP so that it finds the def file for linking?

**Comment by Maurice-Betzel** [comment]
...wait for it, the maven profile...

**Comment by Maurice-Betzel** [comment]
Now the build fails for macos with

[INFO] Compiling /Users/betzm/IdeaProjects/javacpp-presets/libpostal/target/classes/org/bytedeco/javacpp/macosx-x86_64/libjnilibpostal.dylib
[INFO] clang++ -I/Users/betzm/IdeaProjects/javacpp-presets/libpostal/cppbuild/macosx-x86_64/include/ -I/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/include/darwin /Users/betzm/IdeaProjects/javacpp-presets/libpostal/target/classes/org/bytedeco/javacpp/jnilibpostal.cpp /Users/betzm/IdeaProjects/javacpp-presets/libpostal/target/classes/org/bytedeco/javacpp/jnijavacpp.cpp -march=x86-64 -m64 -O3 -Wl,-rpath,@loader_path/. -Wall -fPIC -dynamiclib -undefined dynamic_lookup -o libjnilibpostal.dylib -L/Users/betzm/IdeaProjects/javacpp-presets/libpostal/cppbuild/macosx-x86_64/lib/ -Wl,-rpath,/Users/betzm/IdeaProjects/javacpp-presets/libpostal/cppbuild/macosx-x86_64/lib/ -llibpostal -framework JavaVM 
ld: library not found for -llibpostal
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:19 min
[INFO] Finished at: 2018-01-08T10:18:44+01:00
[INFO] Final Memory: 23M/217M
[INFO] ------------------------------------------------------------------------

I think this is because of the liblibpostal.dylib issue. How can i avoid this requirement of a double lib notation?

**Comment by Maurice-Betzel** [comment]
I can steer this isue with the Platform anotation, resulting in a link naming of 'postal' in the preset which i find confusing. So i kept a copy command to liblibpostal in the cppbuild.sh for macos and linux.

**Comment by saudet** [comment]
The correct linker option for GCC is -lpostal, NOT -llibpostal.

**Comment by Maurice-Betzel** [comment]
Indeed, so you say configure this in the preset?

**Comment by saudet** [comment]
What do you mean? Don't write link="libpostal".

**Comment by Maurice-Betzel** [comment]
Yes, it is ether `cp ../lib/libpostal.dylib ../lib/liblibpostal.dylib` (.so for linux) with link="libpostal" OR no cp and link="postal". Your pick :)

**Comment by saudet** [comment]
Why can't we do exactly like libdc1394?

**Comment by Maurice-Betzel** [comment]
Analog to libdc1394 where `link=dc1394 ` with no lib prefix, that would be option 2 then.

**Comment by Maurice-Betzel** [comment]
Some modules other then libpostal are breaking, as far as i can see by missing dependencies. Is it possible to restart these individually?

**Comment by saudet** [comment]
Yes, but it's not related to libpostal, so don't worry about them. One thing we'll need to fix though is that `libpostal-1.dll` doesn't get bundled. Add a preload like for libdc1394, in this case `preload = "libpostal-1.dll"` and make sure it gets copied. Also, no need of the "oldcompiler" stuff in the `pom.xml`, so clean that to how it was before. :) BTW, I try to order the presets by themes. I guess I'd put "libpostal" just after "llvm"... What do you think? And while we're at it, there are also small but unnecessary changes to the formatting in `.travis.yml`, `.appveyor.yml`, and the main `pom.xml`. Could you clean that up as well? Thanks!

**Comment by saudet** [comment]
Also you forgot to include the version of the link library. It'll probably fail to load on Linux and Mac because of that. We'll need something similar to libdc1394, and I'm guessing `link = "postal@.1"` should work. On Mac, you might also need to patch the configure file to add an `@rpath`, as is done for libdc1394 as well: https://github.com/bytedeco/javacpp-presets/blob/master/libdc1394/libdc1394-2.2.5-macosx.patch

**Comment by Maurice-Betzel** [comment]
Potverdorie, i need to delete my local Maven repo before builing and testing...

**Comment by saudet** [comment]
No you don't need to do that, but you do need to clean up the `target` and `cppbuild` directories, or it will find the libraries there by their install full paths.

**Comment by saudet** [comment]
You'll probably need to add an `@rpath` on Mac as well. What does `otool -L libjniale.dylib` returns?

**Comment by Maurice-Betzel** [comment]
Well, i tested libpostal on all 3 platforms without problems so i thought we might not need the `@rpath`.

**Comment by Maurice-Betzel** [comment]
I just tested all three platforms again, doing a maven clean on the preset and the platform, deleting the maven vectors in my local repo and deleting the .javacpp cache folders. They where all functional without errors. Is the addition of a patch with '@rpath' really needed?

**Comment by saudet** [comment]
Maybe not...

**Comment by saudet** [comment]
It looks like they keep updating `v1.1-alpha`:
https://github.com/openvenues/libpostal/releases
Does it work now?

**Comment by Maurice-Betzel** [comment]
I tested the lib on Centos 7, Windows 10 and MacOS High Sierra, all 64 bit arch, successfully.
Before the test i deleted the local Maven repos of libpostal and the complete .javacpp cache folders and executed a Maven build on the preset and platform module.

**Comment by saudet** [comment]
But you didn't remove the `javacpp-presets` directory itself, so it probably doesn't work... In any case, if `v1.1-alpha` works just as well, let's use that as version!

**Comment by Maurice-Betzel** [comment]
...a Maven clean was included with the build, deleting the project files, I will try the 1.1 version as well.

**Comment by Maurice-Betzel** [comment]
You change the mac configuration on the fly with `sed -i="" 's/-install_name \\$rpath/-install_name @rpath/g' configure`, what is this good for?

**Comment by Maurice-Betzel** [comment]
Got it, the binary can search the dynamic library through a relative path allowing it to run everywhere...

**Comment by saudet** [comment]
We don't need it on Linux. It does what `@rpath` does by default, always has.

**Comment by Maurice-Betzel** [comment]
Still a lot to learn in native land, thanks for your patience. I have put up a [blog post](http://betzelblog.blogspot.nl/2018/01/javacpp-libpostal-preset.html) mentioning the JavaCPP project and your name if that is OK with you.

**Comment by saudet** [comment]
Yes of course, please do! And thanks for the contribution!

**Pull request merged**
