### PR TITLE
Fix mapping of unique pointers

### PR DESCRIPTION
**Pull request by HGuillemet**
When a native function takes a `unique_ptr` to some class as an argument  AND if that class can be instantiated from Java, the Java constructors must by annotated with `@UniquePtr` and `@Name`. 

Affected presets: Pytorch and Tensorflow-lite.

### CODE REVIEW

**Review by saudet — APPROVED** [review]
Looks good, but is there anything else you'd like to fix before the release or is this it?

**Comment by HGuillemet** [comment]
I'm done for the presets. I'm going to push another small fix for javacpp

**Comment by saudet** [comment]
Any estimates on when that fix is going to land?

**Comment by HGuillemet** [comment]
Regression tests on presets are currently running.
I'll check the result in ~ 8 hours.

**Pull request merged**
