### PR TITLE
bump ModSecurity to 3.0.12

### PR DESCRIPTION
**Pull request by paul-hammant**
Newbie attempt at a dep upgrade  ModSecurity from 3.0.8 to 3.0.12

### CODE REVIEW

**Comment by saudet** [comment]
Thanks! We'll also need to update the version in the pom.xml files to 1.5.11-SNAPSHOT and the GitHub Actions workflow to deploy-ubuntu, like other presets.

**Comment by paul-hammant** [comment]
Those two done, and the start of a line in CHANGELOG

**Comment by saudet** [comment]
Instead of trying to change everything at the same time, I'd recommend doing one small change at a time. As for debugging builds, we can do that with https://github.com/mxschmitt/action-tmate

**Comment by paul-hammant** [comment]
I think it's time to admit I've made a mess of this, and should start over in the way you say

**Comment by paul-hammant** [comment]
To be attempted again .. another day

**Pull request closed without merging**
