### PR TITLE
LLVM full optimization

### PR DESCRIPTION
**Pull request by yukoba**
This pull request is for LLVM full optimization.

I added two functions.

1. ```JavaCPPLLVMOptimizeModule()```: This function does the standard LLVM optimization, and based on main() of llvm/tools/opt/opt.cpp.
2. ```JavaCPPLLVMCreateOptimizedJITCompilerForModule()```: This function is similar to LLVMCreateJITCompilerForModule() but does CPU specific optimization.

I added ```JavaCPPLLVM``` prefix to avoid the conflict against LLVM-C function names.

### CODE REVIEW

**Comment by saudet** [comment]
I don't see any `LLVMOptimizeModule()` or `LLVMCreateOptimizedJITCompilerForModule()` functions.
How do those names conflict?

**Comment by yukoba** [comment]
Yes, LLVM does not have ```LLVMOptimizeModule()``` and ```LLVMCreateOptimizedJITCompilerForModule()```. But if LLVM creates those functions in the future, JavaCPP has to change the name and cannot keep the upper compatibility. Therefore I added JavaCPPLLVM prefix.

**Comment by saudet** [comment]
Right, but we're not adding to the C API, so we don't need to follow its conventions. We can also make it more object-oriented. Let me propose something.

**Comment by yukoba** [comment]
Thank you. Please merge.

**Pull request merged**
