### PR TITLE
Fix macosx-arm64 library build for libpostal

### PR DESCRIPTION
**Pull request by MasseGuillaume**

### CODE REVIEW

**Comment by saudet** [comment]
I'm pretty sure libffi works, so instead of trying to modify things randomly, could you try to do it *exactly* the same, including the rpath bit, and check if that works locally on your machine? If that works, there's no reason to try anything different.
https://github.com/bytedeco/javacpp-presets/blob/master/libffi/cppbuild.sh#L86

**Comment by MasseGuillaume** [comment]
Is this the latest jar?
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/libpostal/1.1-1.5.8-SNAPSHOT/libpostal-1.1-1.5.8-20220811.023522-22-macosx-x86_64.jar

if it's the case, we still have X86_64 as architecture

**Comment by saudet** [comment]
Builds from pull requests don't get uploaded anywhere. Check with https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/libpostal/1.1-1.5.8-SNAPSHOT/libpostal-1.1-1.5.8-20220812.040140-28-macosx-arm64.jar

**Comment by MasseGuillaume** [comment]
Got it so you only publish snapshots when it's merged to master.

https://github.com/bytedeco/javacpp-presets/runs/7799698969?check_suite_focus=true#step:2:4855

[INFO] Uploading to sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/libpostal/1.1-1.5.8-SNAPSHOT/libpostal-1.1-1.5.8-20220812.035330-25-macosx-arm64.jar

It looks like the architecture is correct now:

```
❯ otool -hv libjnipostal.dylib  libpostal.1.dylib
libjnipostal.dylib:
Mach header
      magic  cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64    ARM64        ALL  0x00       DYLIB    19       1864   NOUNDEFS DYLDLINK TWOLEVEL WEAK_DEFINES BINDS_TO_WEAK NO_REEXPORTED_DYLIBS
libpostal.1.dylib:
Mach header
      magic  cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64    ARM64        ALL  0x00       DYLIB    15       1632   NOUNDEFS DYLDLINK TWOLEVEL NO_REEXPORTED_DYLIBS
```

**Comment by MasseGuillaume** [comment]
After cleaning up my build tool cache, I was able to run my tests successfully on an M1 chip. Thanks a lot!

**Pull request merged**
