### PR TITLE
Add IPC/SHM to systems

### PR DESCRIPTION
**Pull request by wmeddie**
Adds `shmget`  and related functions to linux and maxosx.

### CODE REVIEW

**Comment by saudet** [comment]
Looks good to me! OK to merge?

**Comment by wmeddie** [comment]
Do we need to add any tests?

**Comment by saudet** [comment]
Nah, just that it compiles is good enough. I run the samples manually before releases to make sure loading works, and that's enough. That reminds me @matsjla is supposed to be working on automating that as part of the Maven build. Any updates?

**Comment by wmeddie** [comment]
I see. If so then it is ready to go from my side.

**Pull request merged**
