### PR TITLE
add ffmpeg-avstream-param.patch

### PR DESCRIPTION
**Pull request by nanguantong**
@saudet  please feel free to merge this patch~

### CODE REVIEW

**Comment by saudet** [comment]
Can you try to contribute this upstream first and see what they say? http://ffmpeg.org/developer.html#Contributing

**Comment by nanguantong** [comment]
`1、int64_t av_stream_get_cur_dts(const AVStream *st);`
    In order to set input AVPackt pts/dts better that avoid "non monotonically increasing dts to muxer in stream" while muxing stream.

`2、void av_stream_set_probe_packets(AVStream *st, int probe_packets);`
    In order to avoid taking too long time for `avformat_find_stream_info` to probe the known codec info (e.g. mpeg audio pcma).

**Comment by nanguantong** [comment]
> 

The AVStream partial parameters had been moved to internal struct FFStream since 5.0 that caused previous call failed in my code.

**Comment by saudet** [comment]
Oh, I see, so they're not going to add this back... Do you have a reference that explains why they moved these parameters internally?

**Comment by nanguantong** [comment]
> Oh, I see, so they're not going to add this back... Do you have a reference that explains why they moved these parameters internally?

Not found detail reasons, only https://github.com/FFmpeg/FFmpeg/commit/591b88e6787c4e678237f02a50421d101abd25c2
https://github.com/FFmpeg/FFmpeg/commit/fab2ed47042d4cc2a4cd69bb97738024c01300c7

**"It's a private fields, no reason to have it exposed in a public header."**

**Comment by saudet** [comment]
It sounds like there's supposed to be another way to set those values, for example, there is a max_probe_packets option:
https://github.com/FFmpeg/FFmpeg/blob/n5.1/libavformat/options_table.h#L108
That doesn't do what you need?

**Comment by nanguantong** [comment]
> 

Option max_probe_packets is another one that different effect, option probe_packets can be set  to interrupt the probe known format at any time that reducing read and write latency.

**Comment by nanguantong** [comment]
When the input stream bitrate is so small (e.g. 256k), the probe processing spends nearly 10 seconds finding the stream info, so long... so that need set the probe_packets = 0 actively.

This is so important issue, please feel free to merge this.

**Comment by nanguantong** [comment]
`2、void av_stream_set_probe_packets(AVStream *st, int probe_packets);`
We found the replaced method to avoid the too long time to probe the stream info. So ignore this issue.

**Comment by saudet** [comment]
> We found the replaced method to avoid the too long time to probe the stream info. So ignore this issue.

Ok, good! What method is that?

And to avoid "non monotonically increasing dts to muxer in stream" I'm pretty sure that setting correct pts/dts values in frames and/or packets should fix that.

**Comment by nanguantong** [comment]
https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/demux.c#L448 set s->probesize = 0 or other smaller value (e.g. 1024* 4).

You'are right, but sometimes stream self pts and dts has some out of order or drop packets, the program do not immediately detect it, so need set 
```
 if (stream.cur_dts() >= outPkt.dts()) {
    outPkt.dts(stream.cur_dts() + 1);
    if (outPkt.pts() < outPkt.dts()) {
        outPkt.pts(outPkt.dts());
    }
 }
ret = av_interleaved_write_frame(ofmtCtx, outPkt);
```

**Comment by saudet** [comment]
There must be some other way to get that information from a stream...

**Comment by nanguantong** [comment]
> There must be some other way to get that information from a stream...

Not found yet.

**Comment by saudet** [comment]
That sounds like a question they could answer upstream: https://ffmpeg.org/contact.html

**Comment by nanguantong** [comment]
https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/mux.c#L543
https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/mux.c#L562

So may use `av_stream_get_end_pts` to replace the stream.cur_pts(), fixed this issue.

                        ```
long endPts = av_stream_get_end_pts(stream);
                        if (endPts >= outPkt.dts()) {
                            outPkt.dts(endPts + 1);
                            if (outPkt.pts() < outPkt.dts()) {
                                outPkt.pts(outPkt.dts());
                            }
                        }
```

**Comment by saudet** [comment]
It looks like cur_pts is simply set to the last pkt->dts, so you could simply do the same in your application:
https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/mux.c#L561

**Comment by nanguantong** [comment]
> It looks like cur_dts is simply set to the last pkt->dts, so you could simply do the same in your application: https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/mux.c#L561

Yes, got it.

**Comment by nanguantong** [comment]
> It looks like cur_dts is simply set to the last pkt->dts, so you could simply do the same in your application: https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/mux.c#L561

Yes, got it.

**Comment by nanguantong** [comment]
> It looks like cur_dts is simply set to the last pkt->dts, so you could simply do the same in your application: https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/mux.c#L561

Yes, got it.

> 

Not simply, ffmpeg changes the input pkt->pts and pkt->dts internally, so not simply save the last input pkt->dts as the cur_dts.

**Comment by nanguantong** [comment]
Okay, I'll try to find other methods to replace the stream.cur_dts, this pr may be closed.

**Comment by saudet** [comment]
Didn't you just agree that pkt.dts, after it gets written, contains the
same information?

**Comment by nanguantong** [comment]
May use the pkt.dts as the last dts, same effect as stream.cur_dts normally, but sometimes not equal, so need to enhance the the processing logic.

**Pull request closed without merging**
