### PR TITLE
Add support for libopus

### PR DESCRIPTION
**Pull request by tdjac0bs**

### CODE REVIEW

**Comment by tdjac0bs** [comment]
Just saw it's not building on some platforms, fixing that.

**Comment by tdjac0bs** [comment]
Hello. This is building correctly here, but it seems travis-ci is with problem.

Can you force the reexecution of the failed tasks?

See the following error, it's about network timeout inside the build container:

image

**Comment by saudet** [comment]
FFmpeg builds are all green on Travis CI AppVeyor, so that looks good! Good
to merge?

**Comment by tdjac0bs** [comment]
Yes, it's working here, please merge it.

**Comment by tdjac0bs** [comment]
Now that it's merged, it should be included in the snapshot build? I want to try the "final" version instead of the locally built one.

**Comment by saudet** [comment]
Yes, they will get uploaded to the SNAPSHOT repository.

**Comment by tdjac0bs** [comment]
Thank you.

**Comment by saudet** [comment]
Thanks to you for the contribution!

**Comment by ishitatsuyuki** [comment]
Just saw this. Why did you use Opus 1.1.5? Is there any compatibility problem? Opus 1.2 has huge advantages.

**Comment by saudet** [comment]
Please send a pull request :)

**Comment by tdjac0bs** [comment]
Hello, i've upgraded to 1.2.

https://github.com/bytedeco/javacpp-presets/pull/460

**Pull request merged**
