### PR TITLE
openvino: work in progress

### PR DESCRIPTION
**Pull request by bradh**

### CODE REVIEW

**Comment by saudet** [comment]
@Grumpy141 @wureka @themarpe FYI, being able to call OpenVINO from Java may be useful to users of DepthAI.

**Comment by themarpe** [comment]
Awesome @bradh - this would allow us to create `blobconverter` equivalent as we have it now in Python, but completely local.

Thanks saudet for the ping :)

**Comment by saudet** [comment]
Duplicate of #1752

**Pull request closed without merging**
